# -*- coding: utf-8 -*-
"""MSG Location+Imagery Collection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wv_5JxQeG2WWO8aNtE5Kpx1vI4uA7K8M
"""

from google.colab import drive
drive.mount('/content/drive')

import os

for root, dirs, files in os.walk('/content/drive/Shareddrives/ISR-NCSES Project/MSG Data'):
    for f in files:
        if 'msg_address_streetview_extract' in f.lower():
            print(os.path.join(root, f))

"""# MSG Data structure check"""

csv_path = r"/content/drive/Shareddrives/ISR-NCSES Project/MSG Data/msg_address_streetview_extract.csv"

import pandas as pd

cols = pd.read_csv(csv_path, nrows=0).columns.tolist()

print(f"{len(cols)} columns found")
for i, col in enumerate(cols):
    print(i, col)

df = pd.read_csv(
    csv_path,
    usecols=["msgid", "latitude", "longitude", "dropcount"]
)

print("rows:", len(df))
print("unique msgid:", df["msgid"].nunique())

print(
    "unique coordinate pairs:",
    df[["latitude", "longitude"]]
      .drop_duplicates()
      .shape[0]
)

print(
    "rows with dropcount > 1:",
    (df["dropcount"] > 1).sum()
)



df = pd.read_csv(csv_path, nrows=5)

df[['fips', 'tract', 'blockgroup', 'block']]

df = pd.read_csv(csv_path, usecols=['fips','tract','blockgroup','block'], nrows=5)

print(df)

"""# Audit using 1,000 location, see if there are images available for each"""

# ============================================================
# MSG Street Imagery Availability Audit
# Platforms:
#   1. Google Street View via streetlevel.streetview
#   2. Bing Streetside via streetlevel.streetside
#   3. Apple Look Around via streetlevel.lookaround
#
# Input:
#   msg_address_streetview_extract.csv
#
# Output:
#   one long metadata table:
#   point_id, query_lat, query_lon, source, available,
#   source_id, capture_date, source_lat, source_lon, dist_m, status, error
# ============================================================

!pip -q install streetlevel aiohttp tqdm pandas openpyxl pillow pillow-heif nest_asyncio

from pathlib import Path
import os
import math
import time
import traceback
import pandas as pd
import aiohttp
import asyncio
import nest_asyncio
from tqdm.auto import tqdm

from streetlevel import streetview, streetside, lookaround

nest_asyncio.apply()

# ============================================================
# 1. Paths and settings
# ============================================================

csv_path = "/content/drive/Shareddrives/ISR-NCSES Project/MSG Data/msg_address_streetview_extract.csv"

OUT_DIR = Path("/content/Shareddrives/ISR-NCSES Project/Street View Collection/MSG_Availability_Audit")

OUT_DIR.mkdir(parents=True, exist_ok=True)

AUDIT_POINTS_CSV = OUT_DIR / "msg_random_1000_points.csv"
OUT_LONG_CSV = OUT_DIR / "msg_random_1000_availability_long.csv"
OUT_WIDE_CSV = OUT_DIR / "msg_random_1000_availability_wide.csv"

N_SAMPLE = 1000
RANDOM_STATE = 42

RADIUS_M = 80
GSV_CONCURRENCY = 10
GSV_TIMEOUT = 120

BING_RADIUS_M = 80
BING_LIMIT = 10

APPLE_SLEEP_SEC = 0.10

# ============================================================
# 2. Helper functions
# ============================================================

def safe_float(x):
    try:
        if pd.isna(x):
            return None
        return float(x)
    except:
        return None


def haversine(lat1, lon1, lat2, lon2):
    if None in (lat1, lon1, lat2, lon2):
        return None

    R = 6371000.0
    phi1, phi2 = math.radians(lat1), math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dlambda = math.radians(lon2 - lon1)

    a = (
        math.sin(dphi / 2) ** 2
        + math.cos(phi1) * math.cos(phi2) * math.sin(dlambda / 2) ** 2
    )

    return 2 * R * math.asin(math.sqrt(a))


def get_obj_latlon(obj):
    lat = getattr(obj, "lat", None)
    lon = getattr(obj, "lon", None)

    if lat is None or lon is None:
        loc = getattr(obj, "location", None)
        if loc is not None:
            lat = getattr(loc, "lat", None)
            lon = getattr(loc, "lon", None)

    return safe_float(lat), safe_float(lon)


def standard_row(point_id, qlat, qlon, source):
    return {
        "point_id": str(point_id),
        "query_lat": qlat,
        "query_lon": qlon,
        "source": source,
        "available": False,
        "source_id": None,
        "capture_date": None,
        "source_lat": None,
        "source_lon": None,
        "dist_m": None,
        "status": None,
        "error": None,
    }

# ============================================================
# 3. Load MSG coordinates and sample 1,000
# ============================================================

points = pd.read_csv(
    csv_path,
    usecols=["msgid", "latitude", "longitude"],
    dtype={"msgid": str}
)

points = points.dropna(subset=["latitude", "longitude"]).copy()
points["latitude"] = points["latitude"].astype(float)
points["longitude"] = points["longitude"].astype(float)
points = points.drop_duplicates(subset=["msgid"])

points = points.rename(columns={
    "msgid": "point_id",
    "latitude": "query_lat",
    "longitude": "query_lon"
})

print("Total usable points:", len(points))

audit_sample = points.sample(
    n=min(N_SAMPLE, len(points)),
    random_state=RANDOM_STATE
).reset_index(drop=True)

audit_sample.to_csv(AUDIT_POINTS_CSV, index=False)

print("Audit sample saved:", AUDIT_POINTS_CSV)
display(audit_sample.head())

# 4. Google Street View availability
#    Uses streetlevel.streetview, same package family as before.

async def check_gsv_one(session, row, sem):
    point_id = str(row["point_id"])
    qlat = float(row["query_lat"])
    qlon = float(row["query_lon"])

    out = standard_row(point_id, qlat, qlon, "google_streetview")

    async with sem:
        try:
            pano = await streetview.find_panorama_async(
                qlat,
                qlon,
                session,
                radius=RADIUS_M
            )

            if pano is None:
                out["status"] = "no_pano"
                return out

            plat, plon = get_obj_latlon(pano)

            out.update({
                "available": True,
                "source_id": str(getattr(pano, "id", None)),
                "capture_date": str(getattr(pano, "date", None)) if getattr(pano, "date", None) else None,
                "source_lat": plat,
                "source_lon": plon,
                "dist_m": haversine(qlat, qlon, plat, plon),
                "status": "ok",
            })

            return out

        except Exception as e:
            out["status"] = "error"
            out["error"] = f"{type(e).__name__}: {e}"
            return out


async def run_gsv_audit(df):
    timeout = aiohttp.ClientTimeout(total=GSV_TIMEOUT)
    sem = asyncio.Semaphore(GSV_CONCURRENCY)

    rows = []
    async with aiohttp.ClientSession(timeout=timeout) as session:
        tasks = [
            check_gsv_one(session, row, sem)
            for _, row in df.iterrows()
        ]

        for coro in tqdm(asyncio.as_completed(tasks), total=len(tasks), desc="Google Street View"):
            rows.append(await coro)

    return pd.DataFrame(rows)


gsv_meta = await run_gsv_audit(audit_sample)

display(gsv_meta.head())
print(gsv_meta["status"].value_counts(dropna=False))

# ============================================================
# 5. Bing Streetside availability
#    Uses streetlevel.streetside.
# ============================================================

def choose_closest_bing_pano(panos, qlat, qlon):
    if not panos:
        return None, None

    best = None
    best_d = float("inf")

    for p in panos:
        plat, plon = get_obj_latlon(p)
        d = haversine(qlat, qlon, plat, plon)
        if d is not None and d < best_d:
            best = p
            best_d = d

    return best, best_d


def check_bing_one(row):
    point_id = str(row["point_id"])
    qlat = float(row["query_lat"])
    qlon = float(row["query_lon"])

    out = standard_row(point_id, qlat, qlon, "bing_streetside")

    try:
        panos = streetside.find_panoramas(
            qlat,
            qlon,
            radius=BING_RADIUS_M,
            limit=BING_LIMIT
        )

        pano, d = choose_closest_bing_pano(panos, qlat, qlon)

        if pano is None:
            out["status"] = "no_pano"
            return out

        plat, plon = get_obj_latlon(pano)

        out.update({
            "available": True,
            "source_id": str(getattr(pano, "id", None)),
            "capture_date": str(getattr(pano, "date", None)) if getattr(pano, "date", None) else None,
            "source_lat": plat,
            "source_lon": plon,
            "dist_m": d,
            "status": "ok",
        })

        return out

    except Exception as e:
        out["status"] = "error"
        out["error"] = f"{type(e).__name__}: {e}"
        return out


bing_rows = []

for _, row in tqdm(audit_sample.iterrows(), total=len(audit_sample), desc="Bing Streetside"):
    bing_rows.append(check_bing_one(row))

bing_meta = pd.DataFrame(bing_rows)

display(bing_meta.head())
print(bing_meta["status"].value_counts(dropna=False))

# ============================================================
# 6. Apple Look Around availability
#    Uses streetlevel.lookaround.
#    Here we only check coverage and nearest pano metadata.
#    No HEIC face download.
# ============================================================

def choose_closest_apple_pano(panos, qlat, qlon):
    if not panos:
        return None, None

    best = None
    best_d = float("inf")

    for p in panos:
        plat, plon = get_obj_latlon(p)
        d = haversine(qlat, qlon, plat, plon)
        if d is not None and d < best_d:
            best = p
            best_d = d

    return best, best_d


def check_apple_one(row):
    point_id = str(row["point_id"])
    qlat = float(row["query_lat"])
    qlon = float(row["query_lon"])

    out = standard_row(point_id, qlat, qlon, "apple_lookaround")

    try:
        tile = lookaround.get_coverage_tile_by_latlon(qlat, qlon)
        panos = getattr(tile, "panos", None) or []

        if len(panos) == 0:
            out["status"] = "no_coverage"
            return out

        pano, d = choose_closest_apple_pano(panos, qlat, qlon)

        if pano is None:
            out["status"] = "no_pano"
            return out

        plat, plon = get_obj_latlon(pano)

        out.update({
            "available": True,
            "source_id": str(getattr(pano, "id", None)),
            "capture_date": str(getattr(pano, "date", None)) if getattr(pano, "date", None) else None,
            "source_lat": plat,
            "source_lon": plon,
            "dist_m": d,
            "status": "ok",
        })

        return out

    except Exception as e:
        out["status"] = "error"
        out["error"] = f"{type(e).__name__}: {e}"
        return out


apple_rows = []

for _, row in tqdm(audit_sample.iterrows(), total=len(audit_sample), desc="Apple Look Around"):
    apple_rows.append(check_apple_one(row))
    time.sleep(APPLE_SLEEP_SEC)

apple_meta = pd.DataFrame(apple_rows)

display(apple_meta.head())
print(apple_meta["status"].value_counts(dropna=False))

# ============================================================
# 6B. Mapillary availability
#    Uses Mapillary Graph API, not streetlevel.
#    Metadata only: closest image within radius.
# ============================================================

!pip -q install requests

import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

MAPILLARY_TOKEN = "MLY|23906238715745799|2d965f9bfc469c30350e928224decb5c"

MAPILLARY_RADIUS_M = 80
MAPILLARY_LIMIT = 50


def make_requests_session():
    s = requests.Session()
    retry = Retry(
        total=5,
        connect=5,
        read=5,
        backoff_factor=0.5,
        status_forcelist=[429, 500, 502, 503, 504],
        allowed_methods=["GET"],
        raise_on_status=False,
    )
    adapter = HTTPAdapter(max_retries=retry, pool_connections=50, pool_maxsize=50)
    s.mount("https://", adapter)
    s.mount("http://", adapter)
    return s


def create_bbox(center_lon, center_lat, radius_meters=80):
    deg_per_meter_lat = 1 / 111000
    deg_per_meter_lon = 1 / (111000 * math.cos(math.radians(center_lat)))

    offset_lat = radius_meters * deg_per_meter_lat
    offset_lon = radius_meters * deg_per_meter_lon

    return (
        center_lon - offset_lon,
        center_lat - offset_lat,
        center_lon + offset_lon,
        center_lat + offset_lat
    )


def check_mapillary_one(row, session):
    point_id = str(row["point_id"])
    qlat = float(row["query_lat"])
    qlon = float(row["query_lon"])

    out = standard_row(point_id, qlat, qlon, "mapillary")

    if MAPILLARY_TOKEN == "PASTE_YOUR_MAPILLARY_TOKEN_HERE":
        out["status"] = "missing_token"
        out["error"] = "Please set MAPILLARY_TOKEN"
        return out

    try:
        west, south, east, north = create_bbox(
            qlon,
            qlat,
            radius_meters=MAPILLARY_RADIUS_M
        )

        bbox_str = f"{west},{south},{east},{north}"

        url = "https://graph.mapillary.com/images"

        params = {
            "access_token": MAPILLARY_TOKEN,
            "bbox": bbox_str,
            "limit": MAPILLARY_LIMIT,
            "fields": "id,captured_at,geometry,compass_angle,camera_type"
        }

        r = session.get(url, params=params, timeout=60)

        if r.status_code != 200:
            out["status"] = "error"
            out["error"] = f"HTTP {r.status_code}: {r.text[:300]}"
            return out

        images = r.json().get("data", [])

        if len(images) == 0:
            out["status"] = "no_image"
            return out

        candidates = []

        for img in images:
            coords = img.get("geometry", {}).get("coordinates", [None, None])
            if coords[0] is None or coords[1] is None:
                continue

            ilon, ilat = coords[0], coords[1]
            d = haversine(qlat, qlon, ilat, ilon)

            if d is None or d > MAPILLARY_RADIUS_M:
                continue

            candidates.append({
                "img": img,
                "source_lat": ilat,
                "source_lon": ilon,
                "dist_m": d
            })

        if len(candidates) == 0:
            out["status"] = "no_image_within_radius"
            return out

        candidates.sort(key=lambda x: x["dist_m"])
        best = candidates[0]
        img = best["img"]

        captured_raw = img.get("captured_at")
        capture_date = None

        if captured_raw is not None:
            ts = pd.to_datetime(captured_raw, unit="ms", errors="coerce", utc=True)
            if not pd.isna(ts):
                capture_date = ts.isoformat()

        out.update({
            "available": True,
            "source_id": str(img.get("id")),
            "capture_date": capture_date,
            "source_lat": best["source_lat"],
            "source_lon": best["source_lon"],
            "dist_m": best["dist_m"],
            "status": "ok",
        })

        return out

    except Exception as e:
        out["status"] = "error"
        out["error"] = f"{type(e).__name__}: {e}"
        return out


mapillary_session = make_requests_session()
mapillary_rows = []

for _, row in tqdm(audit_sample.iterrows(), total=len(audit_sample), desc="Mapillary"):
    mapillary_rows.append(check_mapillary_one(row, mapillary_session))
    time.sleep(0.05)

mapillary_meta = pd.DataFrame(mapillary_rows)

display(mapillary_meta.head())
print(mapillary_meta["status"].value_counts(dropna=False))

# ============================================================
# 7. Combine long metadata table
# ============================================================

availability_long = pd.concat(
    [gsv_meta, bing_meta, apple_meta, mapillary_meta],
    ignore_index=True
)

availability_long.to_csv(OUT_LONG_CSV, index=False, encoding="utf-8-sig")

print("Saved long availability table:", OUT_LONG_CSV)
display(availability_long.head())
print(availability_long.groupby(["source", "status"]).size())

# ============================================================
# 8. Create simple wide summary
# ============================================================

wide_available = availability_long.pivot_table(
    index=["point_id", "query_lat", "query_lon"],
    columns="source",
    values="available",
    aggfunc="first"
).reset_index()

wide_available.columns.name = None

# Add distance columns
wide_dist = availability_long.pivot_table(
    index=["point_id", "query_lat", "query_lon"],
    columns="source",
    values="dist_m",
    aggfunc="first"
).reset_index()

wide_dist.columns.name = None
wide_dist = wide_dist.rename(columns={
    "google_streetview": "google_streetview_dist_m",
    "bing_streetside": "bing_streetside_dist_m",
    "apple_lookaround": "apple_lookaround_dist_m",
    "mapillary": "mapillary_dist_m",
})

availability_wide = wide_available.merge(
    wide_dist,
    on=["point_id", "query_lat", "query_lon"],
    how="left"
)

availability_wide.to_csv(OUT_WIDE_CSV, index=False, encoding="utf-8-sig")

print("Saved wide availability table:", OUT_WIDE_CSV)
display(availability_wide.head())

# ============================================================
# 9. Quick coverage summary
# ============================================================

summary = (
    availability_long
    .groupby("source")
    .agg(
        n_points=("point_id", "count"),
        n_available=("available", "sum"),
        availability_rate=("available", "mean"),
        median_dist_m=("dist_m", "median"),
        mean_dist_m=("dist_m", "mean"),
    )
    .reset_index()
)

display(summary)

# How many addresses have at least one platform available?
any_available = (
    availability_long
    .groupby("point_id")["available"]
    .any()
    .reset_index(name="any_available")
)

print(any_available["any_available"].value_counts(dropna=False))
print("Any-platform availability rate:", any_available["any_available"].mean())



"""# Full audit for all locations"""

# ============================================================
# FULL MSG Availability Audit: GSV + Bing + Apple
# No Mapillary in this full run
# ============================================================

# ----------------------------
# 1. Output paths
# ----------------------------

OUT_DIR = Path("/content/Shareddrives/ISR-NCSES Project/Street View Collection/MSG_Availability_Audit")
OUT_DIR.mkdir(parents=True, exist_ok=True)

FULL_POINTS_CSV = OUT_DIR / "msg_all_points.csv"
OUT_LONG_CSV = OUT_DIR / "msg_all_availability_gsv_bing_apple_long.csv"
OUT_WIDE_CSV = OUT_DIR / "msg_all_availability_gsv_bing_apple_wide.csv"
OUT_COVERAGE_CSV = OUT_DIR / "msg_all_availability_coverage_summary.csv"
OUT_PATTERN_CSV = OUT_DIR / "msg_all_availability_pattern_summary.csv"
OUT_FALLBACK_CSV = OUT_DIR / "msg_all_availability_fallback_summary.csv"


# ----------------------------
# 2. Load full MSG points
# ----------------------------

points = pd.read_csv(
    csv_path,
    usecols=["msgid", "latitude", "longitude"],
    dtype={"msgid": str}
)

points = points.dropna(subset=["latitude", "longitude"]).copy()
points["latitude"] = points["latitude"].astype(float)
points["longitude"] = points["longitude"].astype(float)
points = points.drop_duplicates(subset=["msgid"])

audit_points = points.rename(columns={
    "msgid": "point_id",
    "latitude": "query_lat",
    "longitude": "query_lon"
}).reset_index(drop=True)

audit_points.to_csv(FULL_POINTS_CSV, index=False, encoding="utf-8-sig")

print("Full audit points:", audit_points.shape)
print("Saved full points:", FULL_POINTS_CSV)
display(audit_points.head())


# ----------------------------
# 3. Run Google Street View
# ----------------------------

start = time.time()

gsv_meta = await run_gsv_audit(audit_points)

print("GSV done in", round((time.time() - start) / 60, 2), "minutes")
display(gsv_meta.head())
print(gsv_meta["status"].value_counts(dropna=False))


# ----------------------------
# 4. Run Bing Streetside
# ----------------------------

start = time.time()

bing_rows = []

for _, row in tqdm(audit_points.iterrows(), total=len(audit_points), desc="Bing Streetside"):
    bing_rows.append(check_bing_one(row))

bing_meta = pd.DataFrame(bing_rows)

print("Bing done in", round((time.time() - start) / 60, 2), "minutes")
display(bing_meta.head())
print(bing_meta["status"].value_counts(dropna=False))


# ----------------------------
# 5. Run Apple Look Around
# ----------------------------

start = time.time()

apple_rows = []

for _, row in tqdm(audit_points.iterrows(), total=len(audit_points), desc="Apple Look Around"):
    apple_rows.append(check_apple_one(row))
    time.sleep(APPLE_SLEEP_SEC)

apple_meta = pd.DataFrame(apple_rows)

print("Apple done in", round((time.time() - start) / 60, 2), "minutes")
display(apple_meta.head())
print(apple_meta["status"].value_counts(dropna=False))


# ----------------------------
# 6. Combine long metadata
# ----------------------------

availability_long = pd.concat(
    [gsv_meta, bing_meta, apple_meta],
    ignore_index=True
)

availability_long.to_csv(OUT_LONG_CSV, index=False, encoding="utf-8-sig")

print("Saved long file:", OUT_LONG_CSV)
display(availability_long.head())

print(
    availability_long
    .groupby(["source", "status"])
    .size()
)


# ----------------------------
# 7. Create wide final file
# ----------------------------

available_wide = availability_long.pivot_table(
    index=["point_id", "query_lat", "query_lon"],
    columns="source",
    values="available",
    aggfunc="first"
).reset_index()

available_wide.columns.name = None

available_wide = available_wide.rename(columns={
    "point_id": "msgid",
    "google_streetview": "gsv_available",
    "bing_streetside": "bing_available",
    "apple_lookaround": "apple_available"
})


dist_wide = availability_long.pivot_table(
    index=["point_id", "query_lat", "query_lon"],
    columns="source",
    values="dist_m",
    aggfunc="first"
).reset_index()

dist_wide.columns.name = None

dist_wide = dist_wide.rename(columns={
    "point_id": "msgid",
    "google_streetview": "gsv_dist_m",
    "bing_streetside": "bing_dist_m",
    "apple_lookaround": "apple_dist_m"
})


date_wide = availability_long.pivot_table(
    index=["point_id", "query_lat", "query_lon"],
    columns="source",
    values="capture_date",
    aggfunc="first"
).reset_index()

date_wide.columns.name = None

date_wide = date_wide.rename(columns={
    "point_id": "msgid",
    "google_streetview": "gsv_capture_date",
    "bing_streetside": "bing_capture_date",
    "apple_lookaround": "apple_capture_date"
})


id_wide = availability_long.pivot_table(
    index=["point_id", "query_lat", "query_lon"],
    columns="source",
    values="source_id",
    aggfunc="first"
).reset_index()

id_wide.columns.name = None

id_wide = id_wide.rename(columns={
    "point_id": "msgid",
    "google_streetview": "gsv_source_id",
    "bing_streetside": "bing_source_id",
    "apple_lookaround": "apple_source_id"
})


coord_lat_wide = availability_long.pivot_table(
    index=["point_id", "query_lat", "query_lon"],
    columns="source",
    values="source_lat",
    aggfunc="first"
).reset_index()

coord_lat_wide.columns.name = None

coord_lat_wide = coord_lat_wide.rename(columns={
    "point_id": "msgid",
    "google_streetview": "gsv_source_lat",
    "bing_streetside": "bing_source_lat",
    "apple_lookaround": "apple_source_lat"
})


coord_lon_wide = availability_long.pivot_table(
    index=["point_id", "query_lat", "query_lon"],
    columns="source",
    values="source_lon",
    aggfunc="first"
).reset_index()

coord_lon_wide.columns.name = None

coord_lon_wide = coord_lon_wide.rename(columns={
    "point_id": "msgid",
    "google_streetview": "gsv_source_lon",
    "bing_streetside": "bing_source_lon",
    "apple_lookaround": "apple_source_lon"
})


final_wide = available_wide.merge(
    dist_wide,
    on=["msgid", "query_lat", "query_lon"],
    how="left"
).merge(
    date_wide,
    on=["msgid", "query_lat", "query_lon"],
    how="left"
).merge(
    id_wide,
    on=["msgid", "query_lat", "query_lon"],
    how="left"
).merge(
    coord_lat_wide,
    on=["msgid", "query_lat", "query_lon"],
    how="left"
).merge(
    coord_lon_wide,
    on=["msgid", "query_lat", "query_lon"],
    how="left"
)

for col in ["gsv_available", "bing_available", "apple_available"]:
    final_wide[col] = final_wide[col].fillna(False).astype(bool)

final_wide["any_available"] = (
    final_wide["gsv_available"]
    | final_wide["bing_available"]
    | final_wide["apple_available"]
)

final_wide.to_csv(OUT_WIDE_CSV, index=False, encoding="utf-8-sig")

print("Saved wide final file:", OUT_WIDE_CSV)
display(final_wide.head())


# ----------------------------
# 8. Coverage summary
# ----------------------------

coverage_summary = (
    availability_long
    .groupby("source")
    .agg(
        n_points=("point_id", "count"),
        n_available=("available", "sum"),
        availability_rate=("available", "mean"),
        median_dist_m=("dist_m", "median"),
        mean_dist_m=("dist_m", "mean"),
    )
    .reset_index()
)

coverage_summary.to_csv(OUT_COVERAGE_CSV, index=False, encoding="utf-8-sig")

print("Saved coverage summary:", OUT_COVERAGE_CSV)
display(coverage_summary)

print("Any-platform availability:")
print(final_wide["any_available"].value_counts(dropna=False))
print("Any-platform availability rate:", final_wide["any_available"].mean())


# ----------------------------
# 9. Coverage pattern summary
# ----------------------------

final_wide["coverage_pattern"] = (
    final_wide["gsv_available"].map({True: "GSV", False: ""}) +
    final_wide["bing_available"].map({True: "+Bing", False: ""}) +
    final_wide["apple_available"].map({True: "+Apple", False: ""})
)

final_wide["coverage_pattern"] = (
    final_wide["coverage_pattern"]
    .str.replace(r"^\+", "", regex=True)
    .replace("", "None")
)

pattern_summary = (
    final_wide["coverage_pattern"]
    .value_counts()
    .reset_index()
)

pattern_summary.columns = ["coverage_pattern", "n_locations"]
pattern_summary["pct"] = pattern_summary["n_locations"] / len(final_wide)

pattern_summary.to_csv(OUT_PATTERN_CSV, index=False, encoding="utf-8-sig")

print("Saved pattern summary:", OUT_PATTERN_CSV)
display(pattern_summary)


# ----------------------------
# 10. Fallback / complementarity summary
# ----------------------------

n = len(final_wide)

gsv_hit = final_wide["gsv_available"]
bing_hit = final_wide["bing_available"]
apple_hit = final_wide["apple_available"]

gsv_miss = ~gsv_hit
bing_miss = ~bing_hit
apple_miss = ~apple_hit

fallback_summary = {
    "total_locations": n,

    "gsv_available": int(gsv_hit.sum()),
    "gsv_missing": int(gsv_miss.sum()),
    "among_gsv_missing_bing_available": int((gsv_miss & bing_hit).sum()),
    "among_gsv_missing_apple_available": int((gsv_miss & apple_hit).sum()),
    "among_gsv_missing_bing_or_apple_available": int((gsv_miss & (bing_hit | apple_hit)).sum()),

    "bing_available": int(bing_hit.sum()),
    "bing_missing": int(bing_miss.sum()),
    "among_bing_missing_gsv_available": int((bing_miss & gsv_hit).sum()),
    "among_bing_missing_apple_available": int((bing_miss & apple_hit).sum()),
    "among_bing_missing_gsv_or_apple_available": int((bing_miss & (gsv_hit | apple_hit)).sum()),

    "apple_available": int(apple_hit.sum()),
    "apple_missing": int(apple_miss.sum()),
    "among_apple_missing_gsv_available": int((apple_miss & gsv_hit).sum()),
    "among_apple_missing_bing_available": int((apple_miss & bing_hit).sum()),
    "among_apple_missing_gsv_or_bing_available": int((apple_miss & (gsv_hit | bing_hit)).sum()),

    "gsv_only": int((gsv_hit & ~bing_hit & ~apple_hit).sum()),
    "bing_only": int((~gsv_hit & bing_hit & ~apple_hit).sum()),
    "apple_only": int((~gsv_hit & ~bing_hit & apple_hit).sum()),

    "gsv_and_bing_only": int((gsv_hit & bing_hit & ~apple_hit).sum()),
    "gsv_and_apple_only": int((gsv_hit & ~bing_hit & apple_hit).sum()),
    "bing_and_apple_only": int((~gsv_hit & bing_hit & apple_hit).sum()),
    "all_three": int((gsv_hit & bing_hit & apple_hit).sum()),

    "any_available": int((gsv_hit | bing_hit | apple_hit).sum()),
    "none_available": int((~(gsv_hit | bing_hit | apple_hit)).sum()),
}

fallback_df = pd.DataFrame(
    [{"metric": k, "value": v} for k, v in fallback_summary.items()]
)

fallback_df["pct_of_total"] = fallback_df["value"] / n

fallback_df.to_csv(OUT_FALLBACK_CSV, index=False, encoding="utf-8-sig")

print("Saved fallback summary:", OUT_FALLBACK_CSV)
display(fallback_df)


# ----------------------------
# 11. Final sanity checks
# ----------------------------

print("Final wide rows:", len(final_wide))
print("Unique msgid:", final_wide["msgid"].nunique())

if len(final_wide) != final_wide["msgid"].nunique():
    print("WARNING: duplicated msgid exists in final_wide")
else:
    print("Good: one row per msgid")

print("Files saved:")
print(OUT_LONG_CSV)
print(OUT_WIDE_CSV)
print(OUT_COVERAGE_CSV)
print(OUT_PATTERN_CSV)
print(OUT_FALLBACK_CSV)



"""# 06.24 Audit 1,000 locations from each PUMA, and check GSV availability"""

# Step 1: Extract unique coordinate pairs
csv_path = r"/content/drive/Shareddrives/ISR-NCSES Project/MSG Data/msg_address_streetview_extract.csv"

cols = [
    "msgid",
    "pumaid",
    "latitude",
    "longitude"
]

df = pd.read_csv(csv_path, usecols=cols)

# remove missing coordinates
df = df.dropna(subset=["latitude", "longitude"])

print("Original rows:", len(df))
print("Unique msgid:", df["msgid"].nunique())

# keep the first msgid encountered for each unique coordinate pair:
unique_coords = (
    df
    .sort_values("msgid")
    .drop_duplicates(
        subset=["latitude", "longitude"],
        keep="first"
    )
    .reset_index(drop=True)
)

print("Unique coordinate pairs:", len(unique_coords))

# Step 2: Count unique PUMAs
print("Unique PUMAs:", unique_coords["pumaid"].nunique())

sorted(unique_coords["pumaid"].unique())

# Step 3: Count unique-coordinate msgids by PUMA
puma_summary = (
    unique_coords
    .groupby("pumaid")
    .agg(
        n_unique_coords=("msgid", "count")
    )
    .reset_index()
    .sort_values(
        "n_unique_coords",
        ascending=False
    )
)

puma_summary

print(puma_summary)

# Step 4: Save the coordinate-level frame
from pathlib import Path

out_dir = Path("/content/drive/Shareddrives/ISR-NCSES Project/Street Imagery")
out_dir.mkdir(parents=True, exist_ok=True)

out_path = out_dir / "msg_unique_coordinates.csv"

unique_coords.to_csv(out_path, index=False, encoding="utf-8-sig")

print("Saved:", out_path)

puma_summary = (
    unique_coords
    .groupby("pumaid")
    .agg(n_unique_coord_msgids=("msgid", "count"))
    .reset_index()
    .sort_values("n_unique_coord_msgids", ascending=False)
)

print("Unique PUMAs:", unique_coords["pumaid"].nunique())
display(puma_summary)
print("Total:", puma_summary["n_unique_coord_msgids"].sum())

# ============================================================
# Sample 2,000 unique-coordinate MSG locations per PUMA
# Run Google Street View availability
# Download 10 example images per PUMA
# ============================================================

from pathlib import Path
import pandas as pd
import aiohttp, asyncio, time, os, math
from tqdm.auto import tqdm
from streetlevel import streetview
from IPython.display import display, Image

# ----------------------------
# Paths
# ----------------------------

OUT_DIR = Path("/content/drive/Shareddrives/ISR-NCSES Project/Street Imagery")
OUT_DIR.mkdir(parents=True, exist_ok=True)

UNIQUE_COORDS_PATH = OUT_DIR / "msg_unique_coordinates.csv"

SAMPLE_CSV = OUT_DIR / "msg_sample_2000_per_puma_unique_coords.csv"
GSV_META_CSV = OUT_DIR / "msg_sample_2000_per_puma_gsv_availability.csv"
GSV_SUMMARY_CSV = OUT_DIR / "msg_sample_2000_per_puma_gsv_summary.csv"

IMG_DIR = OUT_DIR / "gsv_sample_images_10_per_puma"
IMG_DIR.mkdir(parents=True, exist_ok=True)

# ----------------------------
# Settings
# ----------------------------

N_PER_PUMA = 2000
RANDOM_STATE = 42
RADIUS_M = 80
ZOOM = 5
CONCURRENCY = 10
TIMEOUT = 120

# ============================================================
# 1. Load unique-coordinate frame
# ============================================================

unique_coords = pd.read_csv(
    UNIQUE_COORDS_PATH,
    dtype={"msgid": str}
)

unique_coords = unique_coords.dropna(subset=["latitude", "longitude", "pumaid"]).copy()
unique_coords["latitude"] = unique_coords["latitude"].astype(float)
unique_coords["longitude"] = unique_coords["longitude"].astype(float)

print("Rows in unique-coordinate frame:", len(unique_coords))
print("Unique PUMAs:", unique_coords["pumaid"].nunique())

display(
    unique_coords
    .groupby("pumaid")
    .size()
    .reset_index(name="n_unique_coords")
    .sort_values("pumaid")
)

# ============================================================
# 2. Randomly sample up to 2,000 locations per PUMA
# ============================================================

sampled = (
    unique_coords
    .groupby("pumaid", group_keys=False)
    .apply(lambda x: x.sample(n=min(N_PER_PUMA, len(x)), random_state=RANDOM_STATE))
    .reset_index(drop=True)
)

sampled = sampled.rename(columns={
    "msgid": "point_id",
    "latitude": "query_lat",
    "longitude": "query_lon"
})

sampled.to_csv(SAMPLE_CSV, index=False, encoding="utf-8-sig")

print("Sampled rows:", len(sampled))
print("Saved:", SAMPLE_CSV)

display(
    sampled
    .groupby("pumaid")
    .size()
    .reset_index(name="n_sampled")
    .sort_values("pumaid")
)

display(sampled.head())

# ============================================================
# 3. Helper functions for GSV availability
# ============================================================

def safe_float(x):
    try:
        if pd.isna(x):
            return None
        return float(x)
    except:
        return None


def haversine(lat1, lon1, lat2, lon2):
    if None in (lat1, lon1, lat2, lon2):
        return None

    R = 6371000.0
    phi1, phi2 = math.radians(lat1), math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dlambda = math.radians(lon2 - lon1)

    a = (
        math.sin(dphi / 2) ** 2
        + math.cos(phi1) * math.cos(phi2) * math.sin(dlambda / 2) ** 2
    )

    return 2 * R * math.asin(math.sqrt(a))


def get_obj_latlon(obj):
    lat = getattr(obj, "lat", None)
    lon = getattr(obj, "lon", None)

    if lat is None or lon is None:
        loc = getattr(obj, "location", None)
        if loc is not None:
            lat = getattr(loc, "lat", None)
            lon = getattr(loc, "lon", None)

    return safe_float(lat), safe_float(lon)


async def check_gsv_one(session, row, sem):
    point_id = str(row["point_id"])
    pumaid = row["pumaid"]
    qlat = float(row["query_lat"])
    qlon = float(row["query_lon"])

    out = {
        "point_id": point_id,
        "pumaid": pumaid,
        "query_lat": qlat,
        "query_lon": qlon,
        "source": "google_streetview",
        "available": False,
        "source_id": None,
        "capture_date": None,
        "source_lat": None,
        "source_lon": None,
        "dist_m": None,
        "status": None,
        "error": None,
    }

    async with sem:
        try:
            pano = await streetview.find_panorama_async(
                qlat,
                qlon,
                session,
                radius=RADIUS_M
            )

            if pano is None:
                out["status"] = "no_pano"
                return out

            plat, plon = get_obj_latlon(pano)

            out.update({
                "available": True,
                "source_id": str(getattr(pano, "id", None)),
                "capture_date": str(getattr(pano, "date", None)) if getattr(pano, "date", None) else None,
                "source_lat": plat,
                "source_lon": plon,
                "dist_m": haversine(qlat, qlon, plat, plon),
                "status": "ok",
            })

            return out

        except Exception as e:
            out["status"] = "error"
            out["error"] = f"{type(e).__name__}: {e}"
            return out


async def run_gsv_audit(df):
    timeout = aiohttp.ClientTimeout(total=TIMEOUT)
    sem = asyncio.Semaphore(CONCURRENCY)

    rows = []
    async with aiohttp.ClientSession(timeout=timeout) as session:
        tasks = [
            check_gsv_one(session, row, sem)
            for _, row in df.iterrows()
        ]

        for coro in tqdm(asyncio.as_completed(tasks), total=len(tasks), desc="GSV availability"):
            rows.append(await coro)

    return pd.DataFrame(rows)

# ============================================================
# 4. Run GSV availability audit
# ============================================================

start = time.time()

gsv_meta = await run_gsv_audit(sampled)

print("Done in", round((time.time() - start) / 60, 2), "minutes")

gsv_meta.to_csv(GSV_META_CSV, index=False, encoding="utf-8-sig")

print("Saved:", GSV_META_CSV)
display(gsv_meta.head())
print(gsv_meta["status"].value_counts(dropna=False))

# ============================================================
# 5. Availability summary by PUMA
# ============================================================

gsv_summary = (
    gsv_meta
    .groupby("pumaid")
    .agg(
        n_sampled=("point_id", "count"),
        n_available=("available", "sum"),
        availability_rate=("available", "mean"),
        median_dist_m=("dist_m", "median"),
        mean_dist_m=("dist_m", "mean"),
    )
    .reset_index()
    .sort_values("pumaid")
)

gsv_summary.to_csv(GSV_SUMMARY_CSV, index=False, encoding="utf-8-sig")

print("Saved:", GSV_SUMMARY_CSV)
display(gsv_summary)

print("Overall availability rate:", gsv_meta["available"].mean())

# ============================================================
# 6. Download 10 available GSV images per PUMA
# ============================================================

available_sample = (
    gsv_meta[gsv_meta["available"] == True]
    .groupby("pumaid", group_keys=False)
    .apply(lambda x: x.sample(n=min(10, len(x)), random_state=RANDOM_STATE))
    .reset_index(drop=True)
)

print("Images to download:", len(available_sample))
display(
    available_sample
    .groupby("pumaid")
    .size()
    .reset_index(name="n_images")
)

async def download_gsv_image_one(session, row, sem):
    point_id = str(row["point_id"])
    pumaid = str(row["pumaid"])
    qlat = float(row["query_lat"])
    qlon = float(row["query_lon"])

    puma_dir = IMG_DIR / f"puma_{pumaid}"
    puma_dir.mkdir(parents=True, exist_ok=True)

    img_path = puma_dir / f"{point_id}_gsv.jpg"

    if img_path.exists() and img_path.stat().st_size > 0:
        return {
            "point_id": point_id,
            "pumaid": pumaid,
            "image_path": str(img_path),
            "status": "skipped_exists"
        }

    async with sem:
        try:
            pano = await streetview.find_panorama_async(
                qlat,
                qlon,
                session,
                radius=RADIUS_M
            )

            if pano is None:
                return {
                    "point_id": point_id,
                    "pumaid": pumaid,
                    "image_path": None,
                    "status": "no_pano"
                }

            await streetview.download_panorama_async(
                pano,
                path=str(img_path),
                session=session,
                zoom=ZOOM
            )

            return {
                "point_id": point_id,
                "pumaid": pumaid,
                "image_path": str(img_path),
                "status": "ok"
            }

        except Exception as e:
            return {
                "point_id": point_id,
                "pumaid": pumaid,
                "image_path": None,
                "status": "error",
                "error": f"{type(e).__name__}: {e}"
            }


async def download_gsv_images(df):
    timeout = aiohttp.ClientTimeout(total=TIMEOUT)
    sem = asyncio.Semaphore(CONCURRENCY)

    rows = []
    async with aiohttp.ClientSession(timeout=timeout) as session:
        tasks = [
            download_gsv_image_one(session, row, sem)
            for _, row in df.iterrows()
        ]

        for coro in tqdm(asyncio.as_completed(tasks), total=len(tasks), desc="Downloading GSV images"):
            rows.append(await coro)

    return pd.DataFrame(rows)


download_meta = await download_gsv_images(available_sample)

DOWNLOAD_META_CSV = IMG_DIR / "download_meta_10_per_puma.csv"
download_meta.to_csv(DOWNLOAD_META_CSV, index=False, encoding="utf-8-sig")

print("Saved:", DOWNLOAD_META_CSV)
display(download_meta.head())
print(download_meta["status"].value_counts(dropna=False))

# ============================================================
# 7. Display downloaded images grouped by PUMA
# ============================================================

for pumaid in sorted(download_meta["pumaid"].dropna().unique()):
    print(f"\n================ PUMA {pumaid} ================")

    paths = (
        download_meta[
            (download_meta["pumaid"] == pumaid)
            & (download_meta["image_path"].notna())
        ]["image_path"]
        .tolist()
    )

    for path in paths[:10]:
        print(path)
        display(Image(filename=path, width=500))

# puma_summary:
# pumaid
# n_unique_coords

# gsv_summary:
# pumaid
# n_sampled
# n_available
# availability_rate

final_summary = (
    puma_summary
    .merge(
        gsv_summary[
            ["pumaid", "n_sampled", "n_available", "availability_rate"]
        ],
        on="pumaid",
        how="left"
    )
    .sort_values("pumaid")
)

# convert to %
final_summary["availability_pct"] = (
    final_summary["availability_rate"] * 100
).round(1)

# prettier column names
final_summary = final_summary.rename(columns={
    "n_unique_coords": "n_unique_locations",
    "n_sampled": "sampled_locations",
    "n_available": "gsv_available"
})

display(final_summary)

final_summary.to_csv(
    "/content/drive/Shareddrives/ISR-NCSES Project/Street Imagery/puma_gsv_summary.csv",
    index=False,
    encoding="utf-8-sig"
)

print(final_summary.columns.tolist())

email_table = final_summary[[
    "pumaid",
    "n_unique_coord_msgids",
    "availability_pct"
]].copy()

email_table = email_table.rename(columns={
    "pumaid": "PUMA ID",
    "n_unique_coord_msgids": "Unique Locations",
    "availability_pct": "GSV Availability (%)"
})

display(email_table)



"""# 06.28 Downloading Images"""

# ============================================================
# Download GSV images for sampled MSG locations
# Folder structure:
# Street Imagery / Imagery Collection / <pumaid> / <msgid>.jpg
# ============================================================

from pathlib import Path
import pandas as pd
import aiohttp
import asyncio
import time
from tqdm.auto import tqdm
from streetlevel import streetview

# ----------------------------
# Paths
# ----------------------------

BASE_DIR = Path("/content/drive/Shareddrives/ISR-NCSES Project/Street Imagery")
COLLECTION_DIR = BASE_DIR / "Imagery Collection"
COLLECTION_DIR.mkdir(parents=True, exist_ok=True)

SAMPLE_CSV = BASE_DIR / "msg_sample_2000_per_puma_unique_coords.csv"
GSV_META_CSV = BASE_DIR / "msg_sample_2000_per_puma_gsv_availability.csv"

DOWNLOAD_META_CSV = COLLECTION_DIR / "gsv_download_metadata.csv"

# ----------------------------
# Settings
# ----------------------------

RADIUS_M = 80
ZOOM = 5
CONCURRENCY = 10
TIMEOUT = 120

# ============================================================
# 1. Load sampled locations and GSV availability results
# ============================================================

sampled = pd.read_csv(SAMPLE_CSV, dtype={"point_id": str, "msgid": str})
gsv_meta = pd.read_csv(GSV_META_CSV, dtype={"point_id": str, "msgid": str})

# Standardize ID column
if "msgid" not in sampled.columns and "point_id" in sampled.columns:
    sampled = sampled.rename(columns={"point_id": "msgid"})

if "msgid" not in gsv_meta.columns and "point_id" in gsv_meta.columns:
    gsv_meta = gsv_meta.rename(columns={"point_id": "msgid"})

# Merge sample info with availability metadata
download_frame = sampled.merge(
    gsv_meta[[
        "msgid",
        "available",
        "source_id",
        "capture_date",
        "source_lat",
        "source_lon",
        "dist_m",
        "status"
    ]],
    on="msgid",
    how="left"
)

print("Sampled locations:", len(sampled))
print("Download frame:", len(download_frame))
print(download_frame["available"].value_counts(dropna=False))

display(download_frame.head())

# ============================================================
# 2. Keep only available GSV locations
# ============================================================

to_download = download_frame[download_frame["available"] == True].copy()

print("Available images to download:", len(to_download))

display(
    to_download
    .groupby("pumaid")
    .size()
    .reset_index(name="n_to_download")
    .sort_values("pumaid")
)

# ============================================================
# 3. Download function
# ============================================================

async def download_one_gsv(session, row, sem):
    msgid = str(row["msgid"])
    pumaid = str(row["pumaid"])
    qlat = float(row["query_lat"])
    qlon = float(row["query_lon"])

    puma_dir = COLLECTION_DIR / pumaid
    puma_dir.mkdir(parents=True, exist_ok=True)

    img_path = puma_dir / f"{msgid}.jpg"

    out = {
        "msgid": msgid,
        "pumaid": pumaid,
        "query_lat": qlat,
        "query_lon": qlon,
        "available_from_audit": row.get("available", None),
        "audit_source_id": row.get("source_id", None),
        "audit_capture_date": row.get("capture_date", None),
        "audit_source_lat": row.get("source_lat", None),
        "audit_source_lon": row.get("source_lon", None),
        "audit_dist_m": row.get("dist_m", None),
        "image_path": str(img_path),
        "download_status": None,
        "download_error": None,
    }

    if img_path.exists() and img_path.stat().st_size > 0:
        out["download_status"] = "skipped_exists"
        return out

    async with sem:
        try:
            pano = await streetview.find_panorama_async(
                qlat,
                qlon,
                session,
                radius=RADIUS_M
            )

            if pano is None:
                out["download_status"] = "no_pano_at_download"
                return out

            await streetview.download_panorama_async(
                pano,
                path=str(img_path),
                session=session,
                zoom=ZOOM
            )

            out["download_status"] = "ok"
            return out

        except Exception as e:
            out["download_status"] = "error"
            out["download_error"] = f"{type(e).__name__}: {e}"
            return out

# ============================================================
# 4. Run download
# ============================================================

async def run_downloads(df):
    timeout = aiohttp.ClientTimeout(total=TIMEOUT)
    sem = asyncio.Semaphore(CONCURRENCY)

    rows = []

    async with aiohttp.ClientSession(timeout=timeout) as session:
        tasks = [
            download_one_gsv(session, row, sem)
            for _, row in df.iterrows()
        ]

        for coro in tqdm(asyncio.as_completed(tasks), total=len(tasks), desc="Downloading GSV images"):
            rows.append(await coro)

    return pd.DataFrame(rows)


start = time.time()

download_meta = await run_downloads(to_download)

print("Done in", round((time.time() - start) / 60, 2), "minutes")

download_meta.to_csv(DOWNLOAD_META_CSV, index=False, encoding="utf-8-sig")

print("Saved metadata:", DOWNLOAD_META_CSV)
display(download_meta.head())
print(download_meta["download_status"].value_counts(dropna=False))

# ============================================================
# 5. Confirm downloaded image counts by PUMA
# ============================================================

download_summary = (
    download_meta
    .groupby(["pumaid", "download_status"])
    .size()
    .reset_index(name="n")
    .sort_values(["pumaid", "download_status"])
)

display(download_summary)

SUMMARY_CSV = COLLECTION_DIR / "gsv_download_summary_by_puma.csv"
download_summary.to_csv(SUMMARY_CSV, index=False, encoding="utf-8-sig")

print("Saved summary:", SUMMARY_CSV)