# -*- coding: utf-8 -*-
"""intersection collection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Iddau5aGJzOGKSAbj5VeKLNtR2nfM5ZL
"""

!pip -q install "osmnx>=2.0,<3.0" geopandas scipy scikit-learn pyogrio

# mount
from google.colab import drive
drive.mount("/content/drive")

for root, dirs, files in os.walk("/content/drive/MyDrive"):
    for filename in files:
        if "msg_sample_2000_per_puma" in filename.lower():
            print(os.path.join(root, filename))

import os
import re
import pandas as pd
from pathlib import Path

INPUT_CSV = Path(
    "/content/drive/MyDrive/msg_sample_2000_per_puma_unique_coords.csv"
)

print(INPUT_CSV.exists())

import pandas as pd

test = pd.read_csv(INPUT_CSV)

print(test.shape)
print(test.columns.tolist())
display(test.head())



OUTPUT_DIR = Path(
    "/content/drive/MyDrive/Georgetown run"
)



from pathlib import Path

script_path = Path(
    "/content/robust_tiled_nearest_intersections_9_pumas.py"
)

print(script_path.exists())

# Commented out IPython magic to ensure Python compatibility.
# %run /content/robust_tiled_nearest_intersections_9_pumas.py

