# -*- coding: utf-8 -*-
"""Coding_MSA locations Images_using_Gemini.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LlyAZMNq4dnWY5jDATB2mYHxMu3ht4eF
"""





"""# 07.15 First Run"""

!umount -l /content/drive

import os
import asyncio
import re
import pandas as pd
import random
import time
from google.colab import drive, userdata
from google import genai
from google.genai import types
from pydantic import BaseModel, Field
from typing import List

# --- CONFIGURATION ---
START_FRESH = False  # Set to True to completely wipe out old files and start from 0

# --- 1. MOUNT GOOGLE DRIVE & SETUP PATHS ---
drive.mount('/content/drive')

BASE_DIR = "/content/shared_radius"
OUTPUT_DIR = "/content/drive/MyDrive/Detroit Safety&VisualAI AAPOR 2026/Computer Vision"
os.makedirs(OUTPUT_DIR, exist_ok=True)
CSV_PATH = os.path.join(OUTPUT_DIR, "run1 detection.csv")

# Force-delete old CSV if START_FRESH is enabled
if START_FRESH:
    print("🗑️ START_FRESH is True. Wiping out any old or cached CSV files...")
    if os.path.exists(CSV_PATH):
        try:
            os.remove(CSV_PATH)
            print("✅ Successfully deleted existing run1 detection.csv to start fresh!")
            time.sleep(2) # Give the file system a moment to sync the deletion
        except Exception as e:
            print(f"⚠️ Could not delete CSV: {e}")
    else:
        print("✅ No existing CSV found. Starting with a clean slate.")

# Force Google Drive virtual file system to sync the shortcut folder
print("🔄 Waking up Google Drive file system...")
try:
    os.listdir("/content/drive/MyDrive")
    if os.path.exists(BASE_DIR):
        os.listdir(BASE_DIR)
        print("✅ Shortcut successfully synced and found!")
except Exception as e:
    print(f"⚠️ Sync warning: {e}")

# Initialize Gemini Client
client = genai.Client(api_key=userdata.get("GEMINI_API_KEY"))
aclient = client.aio

# --- 2. DEFINE 17 RUBRIC CATEGORIES ---
CATEGORIES = [
    "Overgrown tall weeds and unmanaged grass.",
    "Plywood boards covering windows/doors.",
    "Shattered glass or broken window panes.",
    "Peeling paint or chipped wood on siding/porches.",
    "Missing siding panels and exposed house wrap.",
    "Crumbling concrete porch steps and leaning porch roofs.",
    "Weathered asphalt cracks in the street.",
    "Potholes or severely deteriorated road surface.",
    "Colorful graffiti on walls.",
    "Loose litter or scattered garbage piles.",
    "Wood fence or rusted chain-link fences.",
    "Metal security gate or bars over a residential door.",
    "Liquor, tobacco/vape, or dollar-store retail visible.",
    "Visibly abandoned or inoperable vehicles, such as flat tires, missing parts, broken windows, or long-term immobility signs.",
    "Damaged, missing, leaning, or poorly maintained public fixtures, such as street signs, utility poles, bus stops, or streetlights.",
    "Residential garage or garage door visible.",
    "Window air-conditioning unit visible."
]

# --- 3. STRUCTURED OUTPUT SCHEMA ---
class TriageResult(BaseModel):
    overgrown_weeds: bool = Field(description="Overgrown tall weeds and unmanaged grass.")
    plywood_boards: bool = Field(description="Plywood boards covering windows/doors.")
    shattered_glass: bool = Field(description="Shattered glass or broken window panes.")
    peeling_paint: bool = Field(description="Peeling paint or chipped wood on siding/porches.")
    missing_siding: bool = Field(description="Missing siding panels and exposed house wrap.")
    crumbling_concrete: bool = Field(description="Crumbling concrete porch steps and leaning porch roofs.")
    asphalt_cracks: bool = Field(description="Weathered asphalt cracks in the street.")
    potholes: bool = Field(description="Potholes or severely deteriorated road surface.")
    graffiti: bool = Field(description="Colorful graffiti on walls.")
    loose_litter: bool = Field(description="Loose litter or scattered garbage piles.")
    wood_or_chain_fence: bool = Field(description="Wood fence or rusted chain-link fences.")
    security_gate: bool = Field(description="Metal security gate or bars over a residential door.")
    retail_signs: bool = Field(description="Liquor, tobacco/vape, or dollar-store retail visible.")
    abandoned_vehicles: bool = Field(description="Visibly abandoned or inoperable vehicles, such as flat tires, missing parts, broken windows, or long-term immobility signs.")
    damaged_fixtures: bool = Field(description="Damaged, missing, leaning, or poorly maintained public fixtures, such as street signs, utility poles, bus stops, or streetlights.")
    garage_visible: bool = Field(description="Residential garage or garage door visible.")
    window_ac: bool = Field(description="Window air-conditioning unit visible.")

# Mapping Schema keys directly back to your exact 17 column names
SCHEMA_KEY_MAP = {
    "overgrown_weeds": "Overgrown tall weeds and unmanaged grass.",
    "plywood_boards": "Plywood boards covering windows/doors.",
    "shattered_glass": "Shattered glass or broken window panes.",
    "peeling_paint": "Peeling paint or chipped wood on siding/porches.",
    "missing_siding": "Missing siding panels and exposed house wrap.",
    "crumbling_concrete": "Crumbling concrete porch steps and leaning porch roofs.",
    "asphalt_cracks": "Weathered asphalt cracks in the street.",
    "potholes": "Potholes or severely deteriorated road surface.",
    "graffiti": "Colorful graffiti on walls.",
    "loose_litter": "Loose litter or scattered garbage piles.",
    "wood_or_chain_fence": "Wood fence or rusted chain-link fences.",
    "security_gate": "Metal security gate or bars over a residential door.",
    "retail_signs": "Liquor, tobacco/vape, or dollar-store retail visible.",
    "abandoned_vehicles": "Visibly abandoned or inoperable vehicles, such as flat tires, missing parts, broken windows, or long-term immobility signs.",
    "damaged_fixtures": "Damaged, missing, leaning, or poorly maintained public fixtures, such as street signs, utility poles, bus stops, or streetlights.",
    "garage_visible": "Residential garage or garage door visible.",
    "window_ac": "Window air-conditioning unit visible."
}

# --- 4. MODEL PROMPT ---
PROMPT = """
You are flagging visible cues in street-level panorama images.
Evaluate the image against the 17 indicators requested in the JSON schema.
Only select from the 17 indicators. Flag an indicator only if it is visible in the image.
Do not add any indicators outside the given 17. Do not make assumptions.
If the item is clearly visible, set its corresponding value to true. Otherwise, set it to false.
"""

# --- 5. WORKER COROUTINE ---
async def analyze_image(sem, folder_id, image_id, file_path):
    async with sem:
        try:
            with open(file_path, "rb") as f:
                img_bytes = f.read()
        except Exception as e:
            return {"folder_id": folder_id, "image_id": image_id, "error": f"Failed to read file: {e}", "status": "FAILED"}

        image_part = types.Part.from_bytes(data=img_bytes, mime_type="image/jpeg")
        MAX_RETRIES = 5

        for attempt in range(MAX_RETRIES):
            try:
                response = await aclient.models.generate_content(
                    model="gemini-2.5-flash",
                    contents=[PROMPT, image_part],
                    config=types.GenerateContentConfig(
                        response_mime_type="application/json",
                        response_json_schema=TriageResult.model_json_schema(),
                    ),
                )

                parsed = TriageResult.model_validate_json(response.text)
                result_dict = {
                    "folder_id": folder_id,
                    "image_id": image_id,
                    "status": "SUCCESS"
                }

                parsed_data = parsed.model_dump()
                for schema_key, csv_header in SCHEMA_KEY_MAP.items():
                    result_dict[csv_header] = 1 if parsed_data.get(schema_key) else 0

                return result_dict

            except Exception as e:
                err_msg = str(e)
                if "503" in err_msg or "429" in err_msg or "RESOURCE_EXHAUSTED" in err_msg:
                    wait_time = (2 ** attempt) + random.uniform(0, 1)
                    await asyncio.sleep(wait_time)
                else:
                    return {"folder_id": folder_id, "image_id": image_id, "error": f"API Error: {e}", "status": "FAILED"}

        return {"folder_id": folder_id, "image_id": image_id, "error": "Max retries exceeded", "status": "FAILED"}

# --- 6. MAIN ASYNC COORDINATOR ---
async def main():
    processed_images = set()
    if os.path.exists(CSV_PATH):
        try:
            existing_df = pd.read_csv(CSV_PATH)
            if 'status' in existing_df.columns:
                success_df = existing_df[existing_df['status'] == 'SUCCESS']
                processed_images = set(zip(success_df['folder_id'].astype(str), success_df['image_id'].astype(str)))
                print(f"🔄 Checkpoint loaded: {len(processed_images)} images successfully completed.")
            else:
                processed_images = set(zip(existing_df['folder_id'].astype(str), existing_df['image_id'].astype(str)))
        except Exception as e:
            print(f"⚠️ Could not load checkpoint. Error: {e}")

    # Gather target subfolders starting with 260
    subfolders = [d for d in os.listdir(BASE_DIR) if re.match(r"^260\d{4}$", d)]
    print(f"📂 Found {len(subfolders)} subfolders matching the criteria.")

    # Loop and gather all image tasks
    all_image_tasks = []
    for s_folder in subfolders:
        folder_path = os.path.join(BASE_DIR, s_folder)
        images = [img for img in os.listdir(folder_path) if img.lower().endswith(('.jpg', '.jpeg'))]

        for image_file in images:
            image_id = re.sub(r"\D", "", image_file)

            # Skip only if successfully processed
            if (str(s_folder), str(image_id)) in processed_images:
                continue

            file_path = os.path.join(folder_path, image_file)
            all_image_tasks.append((s_folder, image_id, file_path))

    total_tasks = len(all_image_tasks)
    print(f"🚀 Found {total_tasks} remaining images to analyze.")
    if total_tasks == 0:
        print("🎉 All images are already processed successfully!")
        return

    # Concurrency control
    sem = asyncio.Semaphore(40)

    chunk_size = 100
    for i in range(0, total_tasks, chunk_size):
        chunk = all_image_tasks[i:i+chunk_size]
        print(f"⚙️ Processing batch {i // chunk_size + 1} / {-(-total_tasks // chunk_size)}...")

        tasks = [analyze_image(sem, folder, img_id, path) for folder, img_id, path in chunk]
        batch_results = await asyncio.gather(*tasks)

        # Save results iteratively
        new_df = pd.DataFrame(batch_results)
        if os.path.exists(CSV_PATH):
            new_df.to_csv(CSV_PATH, mode='a', header=False, index=False)
        else:
            new_df.to_csv(CSV_PATH, index=False)

        print(f"💾 Checkpoint saved. Progress: {min(i + chunk_size, total_tasks)} / {total_tasks} images analyzed.")

    print(f"\n🎉 SUCCESS! All image pipeline classifications saved to: {CSV_PATH}")

# Launch the processing loop
await main()





# This copies your entire image directory to Colab's local high-speed disk
!cp -r /content/drive/MyDrive/shared_radius /content/shared_radius



import os
import asyncio
import re
import pandas as pd
import random
import time
from google.colab import drive, userdata
from google import genai
from google.genai import types
from pydantic import BaseModel, Field
from typing import List

# --- CONFIGURATION ---
START_FRESH = False  # SET TO TRUE: Guarantees a completely clean slate for the Georgetown run

# --- 1. MOUNT GOOGLE DRIVE & SETUP PATHS ---
drive.mount('/content/drive')

BASE_DIR = "/content/drive/MyDrive/Imagery Collection"
OUTPUT_DIR = "/content/drive/MyDrive/Georgetown run"
os.makedirs(OUTPUT_DIR, exist_ok=True)
CSV_PATH = os.path.join(OUTPUT_DIR, "run1 detection.csv")

# Force-delete old CSV if START_FRESH is enabled
if START_FRESH:
    print("🗑️ START_FRESH is True. Wiping out any old or cached CSV files...")
    if os.path.exists(CSV_PATH):
        try:
            os.remove(CSV_PATH)
            print("✅ Successfully deleted existing run1 detection.csv to start fresh!")
            time.sleep(2) # Give the file system a moment to sync the deletion
        except Exception as e:
            print(f"⚠️ Could not delete CSV: {e}")
    else:
        print("✅ No existing CSV found. Starting with a clean slate.")

# Force Google Drive virtual file system to sync the shortcut folder
print("🔄 Waking up Google Drive file system...")
try:
    os.listdir("/content/drive/MyDrive")
    if os.path.exists(BASE_DIR):
        os.listdir(BASE_DIR)
        print("✅ Directory successfully synced and found!")
except Exception as e:
    print(f"⚠️ Sync warning: {e}")

# Initialize Gemini Client
client = genai.Client(api_key=userdata.get("GEMINI_API_KEY"))
aclient = client.aio

# --- 2. DEFINE 17 RUBRIC CATEGORIES ---
CATEGORIES = [
    "Overgrown tall weeds and unmanaged grass.",
    "Plywood boards covering windows/doors.",
    "Shattered glass or broken window panes.",
    "Peeling paint or chipped wood on siding/porches.",
    "Missing siding panels and exposed house wrap.",
    "Crumbling concrete porch steps and leaning porch roofs.",
    "Weathered asphalt cracks in the street.",
    "Potholes or severely deteriorated road surface.",
    "Colorful graffiti on walls.",
    "Loose litter or scattered garbage piles.",
    "Wood fence or rusted chain-link fences.",
    "Metal security gate or bars over a residential door.",
    "Liquor, tobacco/vape, or dollar-store retail visible.",
    "Visibly abandoned or inoperable vehicles, such as flat tires, missing parts, broken windows, or long-term immobility signs.",
    "Damaged, missing, leaning, or poorly maintained public fixtures, such as street signs, utility poles, bus stops, or streetlights.",
    "Residential garage or garage door visible.",
    "Window air-conditioning unit visible."
]

# --- 3. STRUCTURED OUTPUT SCHEMA ---
class TriageResult(BaseModel):
    overgrown_weeds: bool = Field(description="Overgrown tall weeds and unmanaged grass.")
    plywood_boards: bool = Field(description="Plywood boards covering windows/doors.")
    shattered_glass: bool = Field(description="Shattered glass or broken window panes.")
    peeling_paint: bool = Field(description="Peeling paint or chipped wood on siding/porches.")
    missing_siding: bool = Field(description="Missing siding panels and exposed house wrap.")
    crumbling_concrete: bool = Field(description="Crumbling concrete porch steps and leaning porch roofs.")
    asphalt_cracks: bool = Field(description="Weathered asphalt cracks in the street.")
    potholes: bool = Field(description="Potholes or severely deteriorated road surface.")
    graffiti: bool = Field(description="Colorful graffiti on walls.")
    loose_litter: bool = Field(description="Loose litter or scattered garbage piles.")
    wood_or_chain_fence: bool = Field(description="Wood fence or rusted chain-link fences.")
    security_gate: bool = Field(description="Metal security gate or bars over a residential door.")
    retail_signs: bool = Field(description="Liquor, tobacco/vape, or dollar-store retail visible.")
    abandoned_vehicles: bool = Field(description="Visibly abandoned or inoperable vehicles, such as flat tires, missing parts, broken windows, or long-term immobility signs.")
    damaged_fixtures: bool = Field(description="Damaged, missing, leaning, or poorly maintained public fixtures, such as street signs, utility poles, bus stops, or streetlights.")
    garage_visible: bool = Field(description="Residential garage or garage door visible.")
    window_ac: bool = Field(description="Window air-conditioning unit visible.")

# Mapping Schema keys directly back to your exact 17 column names
SCHEMA_KEY_MAP = {
    "overgrown_weeds": "Overgrown tall weeds and unmanaged grass.",
    "plywood_boards": "Plywood boards covering windows/doors.",
    "shattered_glass": "Shattered glass or broken window panes.",
    "peeling_paint": "Peeling paint or chipped wood on siding/porches.",
    "missing_siding": "Missing siding panels and exposed house wrap.",
    "crumbling_concrete": "Crumbling concrete porch steps and leaning porch roofs.",
    "asphalt_cracks": "Weathered asphalt cracks in the street.",
    "potholes": "Potholes or severely deteriorated road surface.",
    "graffiti": "Colorful graffiti on walls.",
    "loose_litter": "Loose litter or scattered garbage piles.",
    "wood_or_chain_fence": "Wood fence or rusted chain-link fences.",
    "security_gate": "Metal security gate or bars over a residential door.",
    "retail_signs": "Liquor, tobacco/vape, or dollar-store retail visible.",
    "abandoned_vehicles": "Visibly abandoned or inoperable vehicles, such as flat tires, missing parts, broken windows, or long-term immobility signs.",
    "damaged_fixtures": "Damaged, missing, leaning, or poorly maintained public fixtures, such as street signs, utility poles, bus stops, or streetlights.",
    "garage_visible": "Residential garage or garage door visible.",
    "window_ac": "Window air-conditioning unit visible."
}

# --- 4. MODEL PROMPT ---
PROMPT = """
You are flagging visible cues in street-level panorama images.
Evaluate the image against the 17 indicators requested in the JSON schema.
Only select from the 17 indicators. Flag an indicator only if it is visible in the image.
Do not add any indicators outside the given 17. Do not make assumptions.
If the item is clearly visible, set its corresponding value to true. Otherwise, set it to false.
"""

# --- 5. WORKER COROUTINE ---
async def analyze_image(sem, folder_id, image_id, file_path):
    async with sem:
        # Prevent hitting rate limits by adding a tiny staggered delay inside the lock
        await asyncio.sleep(random.uniform(0.1, 0.3))

        try:
            with open(file_path, "rb") as f:
                img_bytes = f.read()
        except Exception as e:
            return {"folder_id": folder_id, "image_id": image_id, "error": f"Failed to read file: {e}", "status": "FAILED"}

        image_part = types.Part.from_bytes(data=img_bytes, mime_type="image/jpeg")
        MAX_RETRIES = 4  # Increased limit to safely handle transient API limits

        for attempt in range(MAX_RETRIES):
            try:
                response = await aclient.models.generate_content(
                    model="gemini-3.1-flash-lite",
                    contents=[PROMPT, image_part],
                    config=types.GenerateContentConfig(
                        response_mime_type="application/json",
                        response_json_schema=TriageResult.model_json_schema(),
                    ),
                )

                parsed = TriageResult.model_validate_json(response.text)
                result_dict = {
                    "folder_id": folder_id,
                    "image_id": image_id,
                    "status": "SUCCESS"
                }

                parsed_data = parsed.model_dump()
                for schema_key, csv_header in SCHEMA_KEY_MAP.items():
                    result_dict[csv_header] = 1 if parsed_data.get(schema_key) else 0

                return result_dict

            except Exception as e:
                err_msg = str(e).upper()
                is_transient = any(x in err_msg for x in ["429", "503", "RESOURCE_EXHAUSTED", "RATE", "QUOTA", "LIMIT", "OVERLOADED"])

                if is_transient and attempt < MAX_RETRIES - 1:
                    wait_time = (2 ** attempt) + random.uniform(1, 3)
                    print(f"⚠️ API Quota limit hit on {image_id}. Retrying in {wait_time:.1f}s...")
                    await asyncio.sleep(wait_time)
                else:
                    return {"folder_id": folder_id, "image_id": image_id, "error": f"API Error: {e}", "status": "FAILED"}

        return {"folder_id": folder_id, "image_id": image_id, "error": "Max retries exceeded", "status": "FAILED"}

# --- 6. MAIN ASYNC COORDINATOR ---
async def main():
    processed_images = set()
    if os.path.exists(CSV_PATH) and not START_FRESH:
        try:
            existing_df = pd.read_csv(CSV_PATH, on_bad_lines='skip')
            if 'status' in existing_df.columns:
                success_df = existing_df[existing_df['status'] == 'SUCCESS']
                processed_images = set(zip(success_df['folder_id'].astype(str), success_df['image_id'].astype(str)))
                print(f"🔄 Checkpoint loaded: {len(processed_images)} images successfully completed.")
            else:
                processed_images = set(zip(existing_df['folder_id'].astype(str), existing_df['image_id'].astype(str)))
        except Exception as e:
            print(f"⚠️ Could not load checkpoint. Error: {e}")

    # Dynamically gather ALL valid subfolders inside the new Imagery Collection folder
    subfolders = sorted(
    [
        d
        for d in os.listdir(BASE_DIR)
        if re.fullmatch(r"260\d{4}", d)
        and os.path.isdir(
            os.path.join(BASE_DIR, d)
        )
    ]
)
    print(f"📂 Found {len(subfolders)} subfolders matching the criteria.")

    # Loop and gather all image tasks
    all_image_tasks = []
    for s_folder in subfolders:
        folder_path = os.path.join(BASE_DIR, s_folder)
        images = [img for img in os.listdir(folder_path) if img.lower().endswith(('.jpg', '.jpeg'))]

        for image_file in images:
            image_id = re.sub(r"\D", "", image_file)

            # Skipped only if successfully completed and not starting fresh
            if not START_FRESH and (str(s_folder), str(image_id)) in processed_images:
                continue

            file_path = os.path.join(folder_path, image_file)
            all_image_tasks.append((s_folder, image_id, file_path))

    total_tasks = len(all_image_tasks)
    print(f"🚀 Found {total_tasks} total images to analyze for the Georgetown run.")
    if total_tasks == 0:
        print("🎉 No images found to process.")
        return

    # Concurrency control set to 2 to prevent rate-limiting on the new account
    sem = asyncio.Semaphore(10)

    # Chunk size set to 50 for frequent checkpoint saves
    chunk_size = 100
    for i in range(0, total_tasks, chunk_size):
        chunk = all_image_tasks[i:i+chunk_size]
        print(f"⚙️ Processing batch {i // chunk_size + 1} / {-(-total_tasks // chunk_size)}...")

        tasks = [analyze_image(sem, folder, img_id, path) for folder, img_id, path in chunk]
        batch_results = await asyncio.gather(*tasks)

        # Create DataFrame of the current batch results
        new_df = pd.DataFrame(batch_results)

        if os.path.exists(CSV_PATH):
            try:
                # Read the existing CSV in real-time
                existing_df = pd.read_csv(CSV_PATH, on_bad_lines='skip')

                # Coerce target columns to matching types (strings)
                existing_df['folder_id'] = existing_df['folder_id'].astype(str)
                existing_df['image_id'] = existing_df['image_id'].astype(str)
                new_df['folder_id'] = new_df['folder_id'].astype(str)
                new_df['image_id'] = new_df['image_id'].astype(str)

                # Merge new attempts and overwrite matching old runs seamlessly
                combined_df = pd.concat([new_df, existing_df], ignore_index=True)
                combined_df = combined_df.drop_duplicates(subset=['folder_id', 'image_id'], keep='first')

                # Write back the perfectly merged dataset
                combined_df.to_csv(CSV_PATH, index=False)
            except Exception as e:
                print(f"⚠️ Error updating CSV in-place: {e}. Appending to the end instead.")
                new_df.to_csv(CSV_PATH, mode='a', header=False, index=False)
        else:
            new_df.to_csv(CSV_PATH, index=False)

        print(f"💾 Checkpoint saved. Progress: {min(i + chunk_size, total_tasks)} / {total_tasks} images analyzed.")

    print(f"\n🎉 SUCCESS! All image pipeline classifications saved to: {CSV_PATH}")

# Launch the processing loop
await main()



from google.colab import userdata
from google import genai

client = genai.Client(
    api_key=userdata.get("GEMINI_API_KEY")
)

for model in client.models.list():
    name = getattr(model, "name", "")
    if "flash-lite" in name.lower():
        print(name)

from google.colab import userdata
from google import genai

client = genai.Client(
    api_key=userdata.get("GEMINI_API_KEY")
)

try:
    response = client.models.generate_content(
        model="gemini-2.5-flash-lite",
        contents="Reply with exactly: MODEL WORKING"
    )

    print(response.text)

except Exception as e:
    print("ERROR TYPE:")
    print(type(e).__name__)

    print("\nFULL ERROR:")
    print(repr(e))

test_image = (
    "/content/drive/MyDrive/"
    "Imagery Collection/2600100/579354.jpg"
)

with open(test_image, "rb") as f:
    img_bytes = f.read()

image_part = types.Part.from_bytes(
    data=img_bytes,
    mime_type="image/jpeg"
)

try:
    response = client.models.generate_content(
        model="gemini-3.1-flash-lite",
        contents=[PROMPT, image_part],
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
            response_json_schema=TriageResult.model_json_schema(),
        ),
    )

    parsed = TriageResult.model_validate_json(response.text)

    print("SUCCESS")
    print(parsed.model_dump())

except Exception as e:
    print(type(e).__name__)
    print(repr(e))



"""# 07.15 Second Run"""

import os
import asyncio
import re
import pandas as pd
import random
import time

from google.colab import drive, userdata
from google import genai
from google.genai import types
from pydantic import BaseModel, Field


# ============================================================
# CONFIGURATION
# ============================================================

START_FRESH = True
# True:
#   Delete any existing run2 detection.csv and restart from zero.
#
# False:
#   Preserve the existing run2 detection.csv and skip images
#   already recorded as SUCCESS.
#
# Use True only for the first clean run.
# After the first checkpoint is saved, change this to False
# before reconnecting or rerunning.


# ============================================================
# 1. MOUNT GOOGLE DRIVE AND SET UP PATHS
# ============================================================

drive.mount("/content/drive")

# Run 2 image source
BASE_DIR = "/content/drive/MyDrive/shared_radius"

# Run 2 output location
OUTPUT_DIR = "/content/drive/MyDrive/Georgetown run"

os.makedirs(
    OUTPUT_DIR,
    exist_ok=True
)

CSV_PATH = os.path.join(
    OUTPUT_DIR,
    "run2 detection.csv"
)


# ============================================================
# 2. DELETE OLD RUN-2 OUTPUT WHEN STARTING FRESH
# ============================================================

if START_FRESH:
    print(
        "🗑️ START_FRESH is True. "
        "Deleting any existing run2 detection.csv..."
    )

    if os.path.exists(CSV_PATH):
        try:
            os.remove(CSV_PATH)

            print(
                "✅ Existing run2 detection.csv deleted."
            )

            # Give Google Drive a moment to sync the deletion
            time.sleep(2)

        except Exception as error:
            raise RuntimeError(
                "Could not delete the existing run2 output:\n"
                f"{CSV_PATH}\n\n"
                f"Error: {error}"
            )

    else:
        print(
            "✅ No existing run2 detection.csv found. "
            "Starting with a clean slate."
        )


# ============================================================
# 3. CONFIRM THE IMAGE SOURCE IS ACCESSIBLE
# ============================================================

print("🔄 Waking up Google Drive file system...")

# Touch MyDrive first to help Colab sync shortcuts
os.listdir("/content/drive/MyDrive")

if not os.path.isdir(BASE_DIR):
    raise FileNotFoundError(
        "The shared_radius image folder could not be found:\n"
        f"{BASE_DIR}\n\n"
        "Confirm that the shared folder shortcut is present in "
        "the current account's My Drive and is named shared_radius."
    )

try:
    os.listdir(BASE_DIR)

except Exception as error:
    raise RuntimeError(
        "shared_radius exists but could not be read:\n"
        f"{BASE_DIR}\n\n"
        f"Error: {error}"
    )

print("✅ shared_radius successfully synced and found!")


# ============================================================
# 4. INITIALIZE GEMINI CLIENT
# ============================================================

api_key = userdata.get("GEMINI_API_KEY")

if not api_key:
    raise ValueError(
        "GEMINI_API_KEY was not found in Colab Secrets."
    )

client = genai.Client(
    api_key=api_key
)

aclient = client.aio


# ============================================================
# 5. DEFINE THE 17 RUBRIC CATEGORIES
# ============================================================

CATEGORIES = [
    "Overgrown tall weeds and unmanaged grass.",
    "Plywood boards covering windows/doors.",
    "Shattered glass or broken window panes.",
    "Peeling paint or chipped wood on siding/porches.",
    "Missing siding panels and exposed house wrap.",
    "Crumbling concrete porch steps and leaning porch roofs.",
    "Weathered asphalt cracks in the street.",
    "Potholes or severely deteriorated road surface.",
    "Colorful graffiti on walls.",
    "Loose litter or scattered garbage piles.",
    "Wood fence or rusted chain-link fences.",
    "Metal security gate or bars over a residential door.",
    "Liquor, tobacco/vape, or dollar-store retail visible.",
    (
        "Visibly abandoned or inoperable vehicles, such as "
        "flat tires, missing parts, broken windows, or "
        "long-term immobility signs."
    ),
    (
        "Damaged, missing, leaning, or poorly maintained "
        "public fixtures, such as street signs, utility poles, "
        "bus stops, or streetlights."
    ),
    "Residential garage or garage door visible.",
    "Window air-conditioning unit visible."
]


# ============================================================
# 6. STRUCTURED OUTPUT SCHEMA
# ============================================================

class TriageResult(BaseModel):
    overgrown_weeds: bool = Field(
        description=(
            "Overgrown tall weeds and unmanaged grass."
        )
    )

    plywood_boards: bool = Field(
        description=(
            "Plywood boards covering windows/doors."
        )
    )

    shattered_glass: bool = Field(
        description=(
            "Shattered glass or broken window panes."
        )
    )

    peeling_paint: bool = Field(
        description=(
            "Peeling paint or chipped wood on siding/porches."
        )
    )

    missing_siding: bool = Field(
        description=(
            "Missing siding panels and exposed house wrap."
        )
    )

    crumbling_concrete: bool = Field(
        description=(
            "Crumbling concrete porch steps and leaning "
            "porch roofs."
        )
    )

    asphalt_cracks: bool = Field(
        description=(
            "Weathered asphalt cracks in the street."
        )
    )

    potholes: bool = Field(
        description=(
            "Potholes or severely deteriorated road surface."
        )
    )

    graffiti: bool = Field(
        description=(
            "Colorful graffiti on walls."
        )
    )

    loose_litter: bool = Field(
        description=(
            "Loose litter or scattered garbage piles."
        )
    )

    wood_or_chain_fence: bool = Field(
        description=(
            "Wood fence or rusted chain-link fences."
        )
    )

    security_gate: bool = Field(
        description=(
            "Metal security gate or bars over a "
            "residential door."
        )
    )

    retail_signs: bool = Field(
        description=(
            "Liquor, tobacco/vape, or dollar-store retail "
            "visible."
        )
    )

    abandoned_vehicles: bool = Field(
        description=(
            "Visibly abandoned or inoperable vehicles, "
            "such as flat tires, missing parts, broken "
            "windows, or long-term immobility signs."
        )
    )

    damaged_fixtures: bool = Field(
        description=(
            "Damaged, missing, leaning, or poorly maintained "
            "public fixtures, such as street signs, utility "
            "poles, bus stops, or streetlights."
        )
    )

    garage_visible: bool = Field(
        description=(
            "Residential garage or garage door visible."
        )
    )

    window_ac: bool = Field(
        description=(
            "Window air-conditioning unit visible."
        )
    )


# ============================================================
# 7. MAP SCHEMA KEYS TO THE EXACT CSV COLUMN NAMES
# ============================================================

SCHEMA_KEY_MAP = {
    "overgrown_weeds":
        "Overgrown tall weeds and unmanaged grass.",

    "plywood_boards":
        "Plywood boards covering windows/doors.",

    "shattered_glass":
        "Shattered glass or broken window panes.",

    "peeling_paint":
        "Peeling paint or chipped wood on siding/porches.",

    "missing_siding":
        "Missing siding panels and exposed house wrap.",

    "crumbling_concrete":
        (
            "Crumbling concrete porch steps and leaning "
            "porch roofs."
        ),

    "asphalt_cracks":
        "Weathered asphalt cracks in the street.",

    "potholes":
        "Potholes or severely deteriorated road surface.",

    "graffiti":
        "Colorful graffiti on walls.",

    "loose_litter":
        "Loose litter or scattered garbage piles.",

    "wood_or_chain_fence":
        "Wood fence or rusted chain-link fences.",

    "security_gate":
        (
            "Metal security gate or bars over a "
            "residential door."
        ),

    "retail_signs":
        (
            "Liquor, tobacco/vape, or dollar-store retail "
            "visible."
        ),

    "abandoned_vehicles":
        (
            "Visibly abandoned or inoperable vehicles, "
            "such as flat tires, missing parts, broken "
            "windows, or long-term immobility signs."
        ),

    "damaged_fixtures":
        (
            "Damaged, missing, leaning, or poorly maintained "
            "public fixtures, such as street signs, utility "
            "poles, bus stops, or streetlights."
        ),

    "garage_visible":
        "Residential garage or garage door visible.",

    "window_ac":
        "Window air-conditioning unit visible."
}


# ============================================================
# 8. MODEL PROMPT
# ============================================================

PROMPT = """
You are flagging visible cues in street-level panorama images.
Evaluate the image against the 17 indicators requested in the JSON schema.
Only select from the 17 indicators. Flag an indicator only if it is visible in the image.
Do not add any indicators outside the given 17. Do not make assumptions.
If the item is clearly visible, set its corresponding value to true. Otherwise, set it to false.
"""


# ============================================================
# 9. FIXED CSV STRUCTURE
# ============================================================

OUTPUT_COLUMNS = [
    "folder_id",
    "image_id",
    "status",
    *SCHEMA_KEY_MAP.values(),
    "error"
]


def empty_result_row(
    folder_id,
    image_id,
    status,
    error=None
):
    """
    Create a result row with the exact same columns every time.
    This prevents failed rows from corrupting CSV column alignment.
    """

    result = {
        "folder_id": str(folder_id),
        "image_id": str(image_id),
        "status": status
    }

    for csv_header in SCHEMA_KEY_MAP.values():
        result[csv_header] = None

    result["error"] = error

    return result


# ============================================================
# 10. WORKER COROUTINE
# ============================================================

async def analyze_image(
    semaphore,
    folder_id,
    image_id,
    file_path
):
    async with semaphore:

        # Small stagger to reduce simultaneous API bursts
        await asyncio.sleep(
            random.uniform(1.0, 2.0)
        )

        try:
            with open(file_path, "rb") as image_file:
                image_bytes = image_file.read()

        except Exception as error:
            return empty_result_row(
                folder_id=folder_id,
                image_id=image_id,
                status="FAILED",
                error=(
                    f"Failed to read file: "
                    f"{type(error).__name__}: {error}"
                )
            )

        image_part = types.Part.from_bytes(
            data=image_bytes,
            mime_type="image/jpeg"
        )

        max_retries = 4

        for attempt in range(max_retries):

            try:
                response = await aclient.models.generate_content(
                    model="gemini-2.5-flash",
                    contents=[
                        PROMPT,
                        image_part
                    ],
                    config=types.GenerateContentConfig(
                        response_mime_type="application/json",
                        response_json_schema=(
                            TriageResult.model_json_schema()
                        )
                    )
                )

                parsed = TriageResult.model_validate_json(
                    response.text
                )

                parsed_data = parsed.model_dump()

                result = empty_result_row(
                    folder_id=folder_id,
                    image_id=image_id,
                    status="SUCCESS",
                    error=None
                )

                for (
                    schema_key,
                    csv_header
                ) in SCHEMA_KEY_MAP.items():

                    result[csv_header] = (
                        1
                        if parsed_data.get(schema_key)
                        else 0
                    )

                return result

            except Exception as error:
                error_text = str(error).upper()

                transient_markers = [
                    "429",
                    "503",
                    "RESOURCE_EXHAUSTED",
                    "RATE",
                    "QUOTA",
                    "LIMIT",
                    "OVERLOADED",
                    "UNAVAILABLE"
                ]

                is_transient = any(
                    marker in error_text
                    for marker in transient_markers
                )

                has_retry_remaining = (
                    attempt < max_retries - 1
                )

                if is_transient and has_retry_remaining:
                    wait_time = (
                        (2 ** attempt)
                        + random.uniform(1, 3)
                    )

                    print(
                        f"⚠️ API limit on {image_id}. "
                        f"Retry {attempt + 1}/{max_retries} "
                        f"in {wait_time:.1f}s..."
                    )

                    await asyncio.sleep(
                        wait_time
                    )

                    continue

                full_error = (
                    f"{type(error).__name__}: {repr(error)}"
                )

                print(
                    f"\n❌ Failed image {image_id}:\n"
                    f"{full_error}\n"
                )

                return empty_result_row(
                    folder_id=folder_id,
                    image_id=image_id,
                    status="FAILED",
                    error=full_error
                )

        return empty_result_row(
            folder_id=folder_id,
            image_id=image_id,
            status="FAILED",
            error="Max retries exceeded"
        )


# ============================================================
# 11. SAVE OR UPDATE THE CHECKPOINT
# ============================================================

def save_checkpoint(
    batch_results
):
    """
    Merge the newest batch with the existing run-2 output.

    New results replace older results for the same folder_id
    and image_id. All rows retain the exact same column order.
    """

    new_df = pd.DataFrame(
        batch_results
    )

    new_df = new_df.reindex(
        columns=OUTPUT_COLUMNS
    )

    new_df["folder_id"] = (
        new_df["folder_id"]
        .astype(str)
    )

    new_df["image_id"] = (
        new_df["image_id"]
        .astype(str)
    )

    if os.path.exists(CSV_PATH):
        existing_df = pd.read_csv(
            CSV_PATH,
            on_bad_lines="skip",
            dtype={
                "folder_id": str,
                "image_id": str
            }
        )

        existing_df = existing_df.reindex(
            columns=OUTPUT_COLUMNS
        )

        combined_df = pd.concat(
            [
                new_df,
                existing_df
            ],
            ignore_index=True
        )

        combined_df = combined_df.drop_duplicates(
            subset=[
                "folder_id",
                "image_id"
            ],
            keep="first"
        )

    else:
        combined_df = new_df

    combined_df = combined_df.sort_values(
        [
            "folder_id",
            "image_id"
        ]
    ).reset_index(
        drop=True
    )

    temporary_path = (
        CSV_PATH
        + ".tmp"
    )

    combined_df.to_csv(
        temporary_path,
        index=False
    )

    os.replace(
        temporary_path,
        CSV_PATH
    )

    return combined_df


# ============================================================
# 12. MAIN ASYNC COORDINATOR
# ============================================================

async def main():

    processed_images = set()

    # --------------------------------------------------------
    # Load successfully processed images when resuming
    # --------------------------------------------------------

    if (
        os.path.exists(CSV_PATH)
        and not START_FRESH
    ):
        try:
            existing_df = pd.read_csv(
                CSV_PATH,
                on_bad_lines="skip",
                dtype={
                    "folder_id": str,
                    "image_id": str
                }
            )

            if "status" in existing_df.columns:
                success_df = existing_df[
                    existing_df["status"].eq(
                        "SUCCESS"
                    )
                ]

                processed_images = set(
                    zip(
                        success_df["folder_id"],
                        success_df["image_id"]
                    )
                )

                print(
                    f"🔄 Checkpoint loaded: "
                    f"{len(processed_images):,} images "
                    f"successfully completed."
                )

        except Exception as error:
            print(
                "⚠️ Could not load the checkpoint:\n"
                f"{type(error).__name__}: {error}"
            )


    # --------------------------------------------------------
    # Find only the nine PUMA folders
    # --------------------------------------------------------

    subfolders = sorted(
        [
            folder_name
            for folder_name in os.listdir(
                BASE_DIR
            )
            if re.fullmatch(
                r"260\d{4}",
                folder_name
            )
            and os.path.isdir(
                os.path.join(
                    BASE_DIR,
                    folder_name
                )
            )
        ]
    )

    print(
        f"📂 Found {len(subfolders)} "
        f"PUMA subfolders:"
    )

    for folder_name in subfolders:
        print(folder_name)

    if len(subfolders) != 9:
        raise ValueError(
            f"Expected 9 PUMA folders, "
            f"but found {len(subfolders)}:\n"
            f"{subfolders}"
        )


    # --------------------------------------------------------
    # Gather all image tasks
    # --------------------------------------------------------

    all_image_tasks = []

    total_images_found = 0
    skipped_successful = 0

    for folder_id in subfolders:

        folder_path = os.path.join(
            BASE_DIR,
            folder_id
        )

        image_files = sorted(
            [
                filename
                for filename in os.listdir(
                    folder_path
                )
                if filename.lower().endswith(
                    (
                        ".jpg",
                        ".jpeg"
                    )
                )
            ]
        )

        total_images_found += len(
            image_files
        )

        for image_filename in image_files:

            # Preserve the identifier logic from the original pipeline
            image_id = re.sub(
                r"\D",
                "",
                image_filename
            )

            key = (
                str(folder_id),
                str(image_id)
            )

            if (
                not START_FRESH
                and key in processed_images
            ):
                skipped_successful += 1
                continue

            file_path = os.path.join(
                folder_path,
                image_filename
            )

            all_image_tasks.append(
                (
                    folder_id,
                    image_id,
                    file_path
                )
            )


    total_tasks = len(
        all_image_tasks
    )

    print(
        f"\n🖼️ Total images found in shared_radius: "
        f"{total_images_found:,}"
    )

    print(
        f"✅ Previously successful images skipped: "
        f"{skipped_successful:,}"
    )

    print(
        f"🚀 Remaining images to analyze: "
        f"{total_tasks:,}"
    )

    if total_tasks == 0:
        print(
            "🎉 All images are already processed successfully!"
        )

        return


    # --------------------------------------------------------
    # Processing settings
    # --------------------------------------------------------

    semaphore = asyncio.Semaphore(
        30
    )

    chunk_size = 50

    total_batches = (
        total_tasks
        + chunk_size
        - 1
    ) // chunk_size


    # --------------------------------------------------------
    # Process and checkpoint every batch
    # --------------------------------------------------------

    for start_index in range(
        0,
        total_tasks,
        chunk_size
    ):

        batch_number = (
            start_index
            // chunk_size
        ) + 1

        chunk = all_image_tasks[
            start_index:
            start_index + chunk_size
        ]

        print(
            f"\n⚙️ Processing batch "
            f"{batch_number} / "
            f"{total_batches}..."
        )

        tasks = [
            analyze_image(
                semaphore=semaphore,
                folder_id=folder_id,
                image_id=image_id,
                file_path=file_path
            )
            for (
                folder_id,
                image_id,
                file_path
            ) in chunk
        ]

        batch_results = await asyncio.gather(
            *tasks
        )

        combined_df = save_checkpoint(
            batch_results
        )

        batch_df = pd.DataFrame(
            batch_results
        )

        batch_status_counts = (
            batch_df["status"]
            .value_counts(
                dropna=False
            )
        )

        print(
            f"💾 Checkpoint saved. "
            f"Current run progress: "
            f"{min(start_index + chunk_size, total_tasks):,} "
            f"/ {total_tasks:,}"
        )

        print(
            "Batch statuses:"
        )

        print(
            batch_status_counts
        )

        print(
            f"Rows currently stored in run2 CSV: "
            f"{len(combined_df):,}"
        )


    # --------------------------------------------------------
    # Final report
    # --------------------------------------------------------

    final_df = pd.read_csv(
        CSV_PATH,
        on_bad_lines="skip"
    )

    print(
        "\n🎉 Run 2 processing finished."
    )

    print(
        "\nFinal output:"
    )

    print(
        CSV_PATH
    )

    print(
        "\nFinal status counts:"
    )

    print(
        final_df["status"]
        .value_counts(
            dropna=False
        )
    )


# ============================================================
# 13. LAUNCH RUN 2
# ============================================================

await main()



