# -*- coding: utf-8 -*-
"""Radius Image Collection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/129jKWP0vyjK2Rwc7Qg5cpejVmaqGgwJG
"""

# Commented out IPython magic to ensure Python compatibility.
# ============================================================
# 1. Install packages, upload CSV, mount Drive, and load data
# ============================================================

# %pip install -q streetlevel

from google.colab import drive, files
from pathlib import Path

import pandas as pd
import aiohttp
import asyncio
import time

from tqdm.auto import tqdm
from streetlevel import streetview


# ============================================================
# Upload the CSV from your computer
# ============================================================

from google.colab import files
from pathlib import Path

uploaded = files.upload()

if not uploaded:
    raise FileNotFoundError("No file was uploaded.")

# Use the actual filename assigned by Colab
uploaded_filename = next(iter(uploaded.keys()))

INPUT_CSV = Path("/content") / uploaded_filename

if not INPUT_CSV.exists():
    raise FileNotFoundError(
        f"Uploaded file could not be found:\n{INPUT_CSV}"
    )

print("Uploaded input file:")
print(INPUT_CSV)

# ============================================================
# 3. Mount Google Drive
# ============================================================

drive.mount("/content/drive")


# ============================================================
# 4. Output folders and files
# ============================================================

OUTPUT_DIR = Path(
    "/content/drive/MyDrive/Street Imagery/radius"
)

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

DOWNLOAD_META_CSV = (
    OUTPUT_DIR / "gsv_download_metadata.csv"
)

DOWNLOAD_SUMMARY_CSV = (
    OUTPUT_DIR / "gsv_download_summary_by_puma.csv"
)


# ============================================================
# 5. Download settings
# ============================================================

RADIUS_M = 80
ZOOM = 5
CONCURRENCY = 10
TIMEOUT_SECONDS = 120
CHECKPOINT_EVERY = 100
MINIMUM_FILE_SIZE_BYTES = 10_000


# ============================================================
# 6. Confirm the uploaded file exists
# ============================================================

if not INPUT_CSV.exists():
    raise FileNotFoundError(
        f"Uploaded input file does not exist:\n{INPUT_CSV}"
    )

print("\nInput CSV:")
print(INPUT_CSV)

print("\nOutput folder:")
print(OUTPUT_DIR)


# ============================================================
# 7. Read the CSV
# ============================================================

sampled = pd.read_csv(
    INPUT_CSV,
    dtype={
        "msgid": str,
        "pumaid": str
    },
    low_memory=False
)


# ============================================================
# 8. Confirm required columns
# ============================================================

required_columns = [
    "msgid",
    "pumaid",
    "query_lon",
    "query_lat"
]

missing_columns = [
    column
    for column in required_columns
    if column not in sampled.columns
]

if missing_columns:
    raise ValueError(
        "The CSV is missing these required columns:\n"
        + "\n".join(missing_columns)
    )

print(f"\nRows loaded: {len(sampled):,}")
print("Required columns found:")
print(required_columns)

display(sampled.head())

# ============================================================
# 5. Clean and validate the required columns
# ============================================================

sampled = sampled[required_columns].copy()

sampled["msgid"] = sampled["msgid"].str.strip()
sampled["pumaid"] = sampled["pumaid"].str.strip()

sampled["query_lon"] = pd.to_numeric(
    sampled["query_lon"],
    errors="coerce"
)

sampled["query_lat"] = pd.to_numeric(
    sampled["query_lat"],
    errors="coerce"
)

invalid_rows = sampled[
    sampled["msgid"].isna()
    | sampled["pumaid"].isna()
    | sampled["query_lon"].isna()
    | sampled["query_lat"].isna()
].copy()

if len(invalid_rows) > 0:
    invalid_file = OUTPUT_DIR / "invalid_input_rows.csv"
    invalid_rows.to_csv(
        invalid_file,
        index=False,
        encoding="utf-8-sig"
    )

    print(
        f"\nWarning: {len(invalid_rows):,} rows have missing or invalid "
        f"required values."
    )
    print("They were saved to:")
    print(invalid_file)

sampled = sampled.dropna(
    subset=[
        "msgid",
        "pumaid",
        "query_lon",
        "query_lat"
    ]
).copy()


# ============================================================
# 6. Check identifiers and coordinate ranges
# ============================================================

duplicate_msgids = sampled["msgid"].duplicated(keep=False)

if duplicate_msgids.any():
    duplicate_file = OUTPUT_DIR / "duplicate_msgids.csv"

    sampled.loc[duplicate_msgids].sort_values(
        "msgid"
    ).to_csv(
        duplicate_file,
        index=False,
        encoding="utf-8-sig"
    )

    raise ValueError(
        f"The input contains "
        f"{sampled.loc[duplicate_msgids, 'msgid'].nunique():,} "
        f"duplicated msgid values.\n"
        f"Review:\n{duplicate_file}"
    )

invalid_coordinates = sampled[
    ~sampled["query_lat"].between(-90, 90)
    | ~sampled["query_lon"].between(-180, 180)
]

if len(invalid_coordinates) > 0:
    invalid_coordinate_file = (
        OUTPUT_DIR / "invalid_coordinate_rows.csv"
    )

    invalid_coordinates.to_csv(
        invalid_coordinate_file,
        index=False,
        encoding="utf-8-sig"
    )

    raise ValueError(
        f"{len(invalid_coordinates):,} rows contain invalid coordinates.\n"
        f"Review:\n{invalid_coordinate_file}"
    )

print(f"\nValid sampled locations: {len(sampled):,}")
print(f"Number of PUMAs: {sampled['pumaid'].nunique():,}")

print("\nLocations per PUMA:")
print(
    sampled
    .groupby("pumaid")
    .size()
    .reset_index(name="n_locations")
    .sort_values("pumaid")
    .to_string(index=False)
)


# ============================================================
# 7. Create one folder for each PUMA
# ============================================================

pumaids = sorted(sampled["pumaid"].unique())

for pumaid in pumaids:
    puma_folder = OUTPUT_DIR / pumaid
    puma_folder.mkdir(parents=True, exist_ok=True)

print(f"\nCreated or confirmed {len(pumaids)} PUMA folders.")


# ============================================================
# 8. Load any previous download metadata
# ============================================================

if DOWNLOAD_META_CSV.exists():
    existing_metadata = pd.read_csv(
        DOWNLOAD_META_CSV,
        dtype={
            "msgid": str,
            "pumaid": str
        },
        low_memory=False
    )

    print(
        f"\nLoaded {len(existing_metadata):,} existing metadata records."
    )
else:
    existing_metadata = pd.DataFrame()


# ============================================================
# 9. Helper function for cumulative checkpointing
# ============================================================

def save_metadata_checkpoint(new_rows):
    """
    Combine existing metadata with results from the current run.

    For duplicated msgid values, retain the most recent result.
    """

    new_metadata = pd.DataFrame(new_rows)

    frames = []

    if not existing_metadata.empty:
        frames.append(existing_metadata)

    if not new_metadata.empty:
        frames.append(new_metadata)

    if not frames:
        return pd.DataFrame()

    combined = pd.concat(
        frames,
        ignore_index=True
    )

    combined = combined.drop_duplicates(
        subset=["msgid"],
        keep="last"
    )

    combined = combined.sort_values(
        ["pumaid", "msgid"]
    ).reset_index(drop=True)

    combined.to_csv(
        DOWNLOAD_META_CSV,
        index=False,
        encoding="utf-8-sig"
    )

    return combined


# ============================================================
# 10. Function to download one GSV panorama
# ============================================================

async def download_one_gsv(session, row, semaphore):
    msgid = str(row["msgid"])
    pumaid = str(row["pumaid"])

    query_lat = float(row["query_lat"])
    query_lon = float(row["query_lon"])

    puma_folder = OUTPUT_DIR / pumaid
    puma_folder.mkdir(parents=True, exist_ok=True)

    image_path = puma_folder / f"{msgid}.jpg"

    result = {
        "msgid": msgid,
        "pumaid": pumaid,
        "query_lon": query_lon,
        "query_lat": query_lat,
        "radius_m": RADIUS_M,
        "zoom": ZOOM,
        "image_path": str(image_path),
        "file_size_bytes": None,
        "download_status": None,
        "download_error": None
    }

    # Skip an image that already exists and appears complete
    if (
        image_path.exists()
        and image_path.stat().st_size >= MINIMUM_FILE_SIZE_BYTES
    ):
        result["file_size_bytes"] = image_path.stat().st_size
        result["download_status"] = "skipped_exists"
        return result

    # Remove a previous empty or suspiciously small file
    if image_path.exists():
        try:
            image_path.unlink()
        except OSError:
            pass

    async with semaphore:
        try:
            panorama = await streetview.find_panorama_async(
                query_lat,
                query_lon,
                session,
                radius=RADIUS_M
            )

            if panorama is None:
                result["download_status"] = "no_panorama"
                return result

            await streetview.download_panorama_async(
                panorama,
                path=str(image_path),
                session=session,
                zoom=ZOOM
            )

            if not image_path.exists():
                raise RuntimeError(
                    "The download function finished, but no image "
                    "file was created."
                )

            file_size = image_path.stat().st_size

            if file_size < MINIMUM_FILE_SIZE_BYTES:
                try:
                    image_path.unlink()
                except OSError:
                    pass

                raise RuntimeError(
                    f"The downloaded file was only {file_size:,} bytes "
                    "and may be incomplete."
                )

            result["file_size_bytes"] = file_size
            result["download_status"] = "ok"

            return result

        except Exception as error:
            result["download_status"] = "error"
            result["download_error"] = (
                f"{type(error).__name__}: {error}"
            )

            # Remove a potentially partial download
            if image_path.exists():
                try:
                    if (
                        image_path.stat().st_size
                        < MINIMUM_FILE_SIZE_BYTES
                    ):
                        image_path.unlink()
                except OSError:
                    pass

            return result


# ============================================================
# 11. Run all downloads with checkpointing
# ============================================================

async def run_downloads_with_checkpoint(data):
    timeout = aiohttp.ClientTimeout(
        total=TIMEOUT_SECONDS
    )

    semaphore = asyncio.Semaphore(
        CONCURRENCY
    )

    current_results = []

    async with aiohttp.ClientSession(
        timeout=timeout
    ) as session:

        tasks = [
            download_one_gsv(
                session=session,
                row=row,
                semaphore=semaphore
            )
            for _, row in data.iterrows()
        ]

        completed_tasks = asyncio.as_completed(tasks)

        for completed_number, task in enumerate(
            tqdm(
                completed_tasks,
                total=len(tasks),
                desc="Downloading GSV panoramas"
            ),
            start=1
        ):
            result = await task
            current_results.append(result)

            if completed_number % CHECKPOINT_EVERY == 0:
                combined_metadata = save_metadata_checkpoint(
                    current_results
                )

                print(
                    f"\nCheckpoint saved after "
                    f"{completed_number:,} locations."
                )

                print(
                    combined_metadata[
                        "download_status"
                    ].value_counts(
                        dropna=False
                    )
                )

    return current_results


# ============================================================
# 12. Start the download
# ============================================================

start_time = time.time()

new_results = await run_downloads_with_checkpoint(
    sampled
)

elapsed_minutes = (
    time.time() - start_time
) / 60

print(
    f"\nDownload processing finished in "
    f"{elapsed_minutes:.2f} minutes."
)


# ============================================================
# 13. Save final cumulative metadata
# ============================================================

download_metadata = save_metadata_checkpoint(
    new_results
)

print("\nFinal metadata saved to:")
print(DOWNLOAD_META_CSV)

print("\nDownload statuses:")
print(
    download_metadata[
        "download_status"
    ].value_counts(
        dropna=False
    )
)


# ============================================================
# 14. Create the PUMA-level summary
# ============================================================

download_summary = (
    download_metadata
    .groupby(
        ["pumaid", "download_status"],
        dropna=False
    )
    .size()
    .unstack(
        fill_value=0
    )
    .reset_index()
)

download_summary["n_processed"] = (
    download_summary
    .drop(columns=["pumaid"])
    .sum(axis=1)
)

download_summary.to_csv(
    DOWNLOAD_SUMMARY_CSV,
    index=False,
    encoding="utf-8-sig"
)

print("\nPUMA-level summary saved to:")
print(DOWNLOAD_SUMMARY_CSV)

display(download_summary)