# -*- coding: utf-8 -*-
"""Coding_Neighborhood Images_using_Gemini.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gNDchOdpihUSmk2z10K5XfaJCxPjUaRs
"""

from google.colab import drive
drive.mount("/content/drive")

import os

print(os.listdir("/content/drive/MyDrive/Georgetown run/radius"))

import os
import re
import pandas as pd

BASE_DIR = "/content/drive/MyDrive/Georgetown run/radius"

puma_folders = sorted(
    [
        folder
        for folder in os.listdir(BASE_DIR)
        if re.fullmatch(r"260\d{4}", folder)
        and os.path.isdir(
            os.path.join(BASE_DIR, folder)
        )
    ]
)

counts = []

for pumaid in puma_folders:
    folder_path = os.path.join(BASE_DIR, pumaid)

    n_images = sum(
        filename.lower().endswith((".jpg", ".jpeg"))
        for filename in os.listdir(folder_path)
    )

    counts.append(
        {
            "pumaid": pumaid,
            "n_images": n_images
        }
    )

counts_df = pd.DataFrame(counts)

print("PUMA folders found:", len(counts_df))
print("Total images:", counts_df["n_images"].sum())

display(counts_df)





import os
import re

path = "/content/drive/MyDrive/shared_radius"

for level in range(8):
    print(f"\nLEVEL {level}")
    print("PATH:", path)

    try:
        items = os.listdir(path)
    except Exception as e:
        print("ERROR:", e)
        break

    print("CONTENTS:", items[:30])

    pumas = [
        item for item in items
        if re.fullmatch(r"260\d{4}", item)
        and os.path.isdir(os.path.join(path, item))
    ]

    if pumas:
        print(f"\n✅ FOUND {len(pumas)} PUMA folders")
        print(sorted(pumas))
        print("\nUse this as BASE_DIR:")
        print(path)
        break

    next_path = os.path.join(path, "shared_radius")

    if os.path.isdir(next_path):
        path = next_path
    else:
        print("\n❌ No further shared_radius subfolder found.")
        break





from google.colab import drive

drive.mount(
    "/content/drive",
    force_remount=True
)







"""# Run 2"""

import os
import asyncio
import re
import pandas as pd
import random
import time

from google.colab import drive, userdata
from google import genai
from google.genai import types
from pydantic import BaseModel, Field


# ============================================================
# CONFIGURATION
# ============================================================

# IMPORTANT:
# False preserves the existing run2 detection.csv,
# skips existing SUCCESS rows, and retries all other rows.
START_FRESH = False

MODEL_NAME = "gemini-2.5-flash"

# Conservative retry-pass settings
MAX_CONCURRENT_TASKS = 5
CHUNK_SIZE = 10

# Timeouts
FILE_READ_TIMEOUT_SECONDS = 60
GEMINI_TIMEOUT_SECONDS = 120

# Retries
FILE_READ_RETRIES = 5
GEMINI_RETRIES = 4


# ============================================================
# 1. MOUNT GOOGLE DRIVE AND SET UP PATHS
# ============================================================

drive.mount("/content/drive")

BASE_DIR = (
    "/content/drive/MyDrive/"
    "Georgetown run/radius"
)

OUTPUT_DIR = (
    "/content/drive/MyDrive/"
    "Georgetown run"
)

os.makedirs(
    OUTPUT_DIR,
    exist_ok=True
)

CSV_PATH = os.path.join(
    OUTPUT_DIR,
    "run2 detection.csv"
)


# ============================================================
# 2. OPTIONAL CLEAN RESTART LOGIC
# ============================================================

if START_FRESH:
    print(
        "🗑️ START_FRESH is True. "
        "Deleting any existing run2 detection.csv..."
    )

    if os.path.exists(CSV_PATH):
        try:
            os.remove(CSV_PATH)

            print(
                "✅ Existing run2 detection.csv deleted."
            )

            time.sleep(2)

        except Exception as error:
            raise RuntimeError(
                "Could not delete the existing run2 output:\n"
                f"{CSV_PATH}\n\n"
                f"Error: {type(error).__name__}: {error}"
            )

    else:
        print(
            "✅ No existing run2 detection.csv found. "
            "Starting with a clean slate."
        )


# ============================================================
# 3. CONFIRM IMAGE SOURCE AND OUTPUT ARE ACCESSIBLE
# ============================================================

print("🔄 Waking up Google Drive file system...")

os.listdir("/content/drive/MyDrive")

if not os.path.isdir(BASE_DIR):
    raise FileNotFoundError(
        "The Run 2 image directory could not be found:\n"
        f"{BASE_DIR}"
    )

try:
    os.listdir(BASE_DIR)

except Exception as error:
    raise RuntimeError(
        "The Run 2 image directory exists but could not "
        "be read:\n"
        f"{BASE_DIR}\n\n"
        f"Error: {type(error).__name__}: {error}"
    )

if not os.path.exists(CSV_PATH) and not START_FRESH:
    print(
        "⚠️ START_FRESH is False, but no existing "
        "run2 detection.csv was found."
    )
    print(
        "The script will process all available images."
    )

print("✅ Run 2 image directory successfully found!")
print(f"📁 Image source: {BASE_DIR}")
print(f"📄 Output CSV: {CSV_PATH}")


# ============================================================
# 4. INITIALIZE GEMINI CLIENT
# ============================================================

api_key = userdata.get("GEMINI_API_KEY")

if not api_key:
    raise ValueError(
        "GEMINI_API_KEY was not found in Colab Secrets."
    )

client = genai.Client(
    api_key=api_key
)

aclient = client.aio


# ============================================================
# 5. DEFINE THE 17 RUBRIC CATEGORIES
# ============================================================

CATEGORIES = [
    "Overgrown tall weeds and unmanaged grass.",
    "Plywood boards covering windows/doors.",
    "Shattered glass or broken window panes.",
    "Peeling paint or chipped wood on siding/porches.",
    "Missing siding panels and exposed house wrap.",
    "Crumbling concrete porch steps and leaning porch roofs.",
    "Weathered asphalt cracks in the street.",
    "Potholes or severely deteriorated road surface.",
    "Colorful graffiti on walls.",
    "Loose litter or scattered garbage piles.",
    "Wood fence or rusted chain-link fences.",
    "Metal security gate or bars over a residential door.",
    "Liquor, tobacco/vape, or dollar-store retail visible.",
    (
        "Visibly abandoned or inoperable vehicles, such as "
        "flat tires, missing parts, broken windows, or "
        "long-term immobility signs."
    ),
    (
        "Damaged, missing, leaning, or poorly maintained "
        "public fixtures, such as street signs, utility poles, "
        "bus stops, or streetlights."
    ),
    "Residential garage or garage door visible.",
    "Window air-conditioning unit visible."
]


# ============================================================
# 6. STRUCTURED OUTPUT SCHEMA
# ============================================================

class TriageResult(BaseModel):

    overgrown_weeds: bool = Field(
        description=(
            "Overgrown tall weeds and unmanaged grass."
        )
    )

    plywood_boards: bool = Field(
        description=(
            "Plywood boards covering windows/doors."
        )
    )

    shattered_glass: bool = Field(
        description=(
            "Shattered glass or broken window panes."
        )
    )

    peeling_paint: bool = Field(
        description=(
            "Peeling paint or chipped wood on siding/porches."
        )
    )

    missing_siding: bool = Field(
        description=(
            "Missing siding panels and exposed house wrap."
        )
    )

    crumbling_concrete: bool = Field(
        description=(
            "Crumbling concrete porch steps and leaning "
            "porch roofs."
        )
    )

    asphalt_cracks: bool = Field(
        description=(
            "Weathered asphalt cracks in the street."
        )
    )

    potholes: bool = Field(
        description=(
            "Potholes or severely deteriorated road surface."
        )
    )

    graffiti: bool = Field(
        description=(
            "Colorful graffiti on walls."
        )
    )

    loose_litter: bool = Field(
        description=(
            "Loose litter or scattered garbage piles."
        )
    )

    wood_or_chain_fence: bool = Field(
        description=(
            "Wood fence or rusted chain-link fences."
        )
    )

    security_gate: bool = Field(
        description=(
            "Metal security gate or bars over a "
            "residential door."
        )
    )

    retail_signs: bool = Field(
        description=(
            "Liquor, tobacco/vape, or dollar-store retail "
            "visible."
        )
    )

    abandoned_vehicles: bool = Field(
        description=(
            "Visibly abandoned or inoperable vehicles, "
            "such as flat tires, missing parts, broken "
            "windows, or long-term immobility signs."
        )
    )

    damaged_fixtures: bool = Field(
        description=(
            "Damaged, missing, leaning, or poorly maintained "
            "public fixtures, such as street signs, utility "
            "poles, bus stops, or streetlights."
        )
    )

    garage_visible: bool = Field(
        description=(
            "Residential garage or garage door visible."
        )
    )

    window_ac: bool = Field(
        description=(
            "Window air-conditioning unit visible."
        )
    )


# ============================================================
# 7. MAP SCHEMA KEYS TO EXACT CSV COLUMN NAMES
# ============================================================

SCHEMA_KEY_MAP = {
    "overgrown_weeds":
        "Overgrown tall weeds and unmanaged grass.",

    "plywood_boards":
        "Plywood boards covering windows/doors.",

    "shattered_glass":
        "Shattered glass or broken window panes.",

    "peeling_paint":
        "Peeling paint or chipped wood on siding/porches.",

    "missing_siding":
        "Missing siding panels and exposed house wrap.",

    "crumbling_concrete":
        (
            "Crumbling concrete porch steps and leaning "
            "porch roofs."
        ),

    "asphalt_cracks":
        "Weathered asphalt cracks in the street.",

    "potholes":
        "Potholes or severely deteriorated road surface.",

    "graffiti":
        "Colorful graffiti on walls.",

    "loose_litter":
        "Loose litter or scattered garbage piles.",

    "wood_or_chain_fence":
        "Wood fence or rusted chain-link fences.",

    "security_gate":
        (
            "Metal security gate or bars over a "
            "residential door."
        ),

    "retail_signs":
        (
            "Liquor, tobacco/vape, or dollar-store retail "
            "visible."
        ),

    "abandoned_vehicles":
        (
            "Visibly abandoned or inoperable vehicles, "
            "such as flat tires, missing parts, broken "
            "windows, or long-term immobility signs."
        ),

    "damaged_fixtures":
        (
            "Damaged, missing, leaning, or poorly maintained "
            "public fixtures, such as street signs, utility "
            "poles, bus stops, or streetlights."
        ),

    "garage_visible":
        "Residential garage or garage door visible.",

    "window_ac":
        "Window air-conditioning unit visible."
}


# ============================================================
# 8. MODEL PROMPT
# ============================================================

PROMPT = """
You are flagging visible cues in street-level panorama images.
Evaluate the image against the 17 indicators requested in the JSON schema.
Only select from the 17 indicators. Flag an indicator only if it is visible in the image.
Do not add any indicators outside the given 17. Do not make assumptions.
If the item is clearly visible, set its corresponding value to true. Otherwise, set it to false.
"""


# ============================================================
# 9. FIXED CSV STRUCTURE
# ============================================================

OUTPUT_COLUMNS = [
    "folder_id",
    "image_id",
    "status",
    *SCHEMA_KEY_MAP.values(),
    "error"
]


def empty_result_row(
    folder_id,
    image_id,
    status,
    error=None
):
    """
    Create a result row with exactly the expected CSV columns.
    """

    result = {
        "folder_id": str(folder_id),
        "image_id": str(image_id),
        "status": status
    }

    for csv_header in SCHEMA_KEY_MAP.values():
        result[csv_header] = None

    result["error"] = error

    return result


# ============================================================
# 10. FILE-READ HELPER
# ============================================================

def read_image_bytes(
    file_path
):
    """
    Synchronous file-reading helper.

    It is run through asyncio.to_thread(), allowing the main
    asynchronous event loop to remain responsive.
    """

    with open(file_path, "rb") as image_file:
        image_bytes = image_file.read()

    if not image_bytes:
        raise OSError(
            "The image file was read but returned zero bytes."
        )

    return image_bytes


# ============================================================
# 11. WORKER COROUTINE
# ============================================================

async def analyze_image(
    semaphore,
    folder_id,
    image_id,
    file_path
):
    async with semaphore:

        await asyncio.sleep(
            random.uniform(0.1, 0.3)
        )

        # ----------------------------------------------------
        # Read image from Google Drive with retries and timeout
        # ----------------------------------------------------

        image_bytes = None

        for read_attempt in range(FILE_READ_RETRIES):

            try:
                image_bytes = await asyncio.wait_for(
                    asyncio.to_thread(
                        read_image_bytes,
                        file_path
                    ),
                    timeout=FILE_READ_TIMEOUT_SECONDS
                )

                break

            except asyncio.TimeoutError:
                has_retry_remaining = (
                    read_attempt < FILE_READ_RETRIES - 1
                )

                if has_retry_remaining:
                    wait_time = (
                        (2 ** read_attempt)
                        + random.uniform(0.5, 1.5)
                    )

                    print(
                        f"⚠️ Drive read timeout on {image_id}. "
                        f"Retry {read_attempt + 1}/"
                        f"{FILE_READ_RETRIES} "
                        f"in {wait_time:.1f}s..."
                    )

                    await asyncio.sleep(
                        wait_time
                    )

                    continue

                return empty_result_row(
                    folder_id=folder_id,
                    image_id=image_id,
                    status="FAILED",
                    error=(
                        "TimeoutError: Google Drive file read "
                        f"exceeded {FILE_READ_TIMEOUT_SECONDS} "
                        "seconds after "
                        f"{FILE_READ_RETRIES} attempts."
                    )
                )

            except OSError as error:
                has_retry_remaining = (
                    read_attempt < FILE_READ_RETRIES - 1
                )

                if has_retry_remaining:
                    wait_time = (
                        (2 ** read_attempt)
                        + random.uniform(0.5, 1.5)
                    )

                    print(
                        f"⚠️ Drive read error on {image_id}. "
                        f"Retry {read_attempt + 1}/"
                        f"{FILE_READ_RETRIES} "
                        f"in {wait_time:.1f}s..."
                    )

                    await asyncio.sleep(
                        wait_time
                    )

                    continue

                return empty_result_row(
                    folder_id=folder_id,
                    image_id=image_id,
                    status="FAILED",
                    error=(
                        f"Failed to read file after "
                        f"{FILE_READ_RETRIES} attempts: "
                        f"{type(error).__name__}: {error}"
                    )
                )

            except Exception as error:
                return empty_result_row(
                    folder_id=folder_id,
                    image_id=image_id,
                    status="FAILED",
                    error=(
                        f"Unexpected file-read error: "
                        f"{type(error).__name__}: {error}"
                    )
                )

        if image_bytes is None:
            return empty_result_row(
                folder_id=folder_id,
                image_id=image_id,
                status="FAILED",
                error="Image bytes were not loaded."
            )

        # ----------------------------------------------------
        # Build Gemini image input
        # ----------------------------------------------------

        image_part = types.Part.from_bytes(
            data=image_bytes,
            mime_type="image/jpeg"
        )

        # ----------------------------------------------------
        # Call Gemini with retries and timeout
        # ----------------------------------------------------

        for attempt in range(GEMINI_RETRIES):

            try:
                response = await asyncio.wait_for(
                    aclient.models.generate_content(
                        model=MODEL_NAME,
                        contents=[
                            PROMPT,
                            image_part
                        ],
                        config=types.GenerateContentConfig(
                            response_mime_type=(
                                "application/json"
                            ),
                            response_json_schema=(
                                TriageResult.model_json_schema()
                            )
                        )
                    ),
                    timeout=GEMINI_TIMEOUT_SECONDS
                )

                if not response.text:
                    raise ValueError(
                        "Gemini returned an empty response."
                    )

                parsed = TriageResult.model_validate_json(
                    response.text
                )

                parsed_data = parsed.model_dump()

                result = empty_result_row(
                    folder_id=folder_id,
                    image_id=image_id,
                    status="SUCCESS",
                    error=None
                )

                for (
                    schema_key,
                    csv_header
                ) in SCHEMA_KEY_MAP.items():

                    result[csv_header] = (
                        1
                        if parsed_data.get(schema_key)
                        else 0
                    )

                return result

            except asyncio.TimeoutError:
                has_retry_remaining = (
                    attempt < GEMINI_RETRIES - 1
                )

                if has_retry_remaining:
                    wait_time = (
                        (2 ** attempt)
                        + random.uniform(1, 3)
                    )

                    print(
                        f"⚠️ Gemini timeout on {image_id}. "
                        f"Retry {attempt + 1}/"
                        f"{GEMINI_RETRIES} "
                        f"in {wait_time:.1f}s..."
                    )

                    await asyncio.sleep(
                        wait_time
                    )

                    continue

                full_error = (
                    "TimeoutError: Gemini request exceeded "
                    f"{GEMINI_TIMEOUT_SECONDS} seconds after "
                    f"{GEMINI_RETRIES} attempts."
                )

                print(
                    f"\n❌ Failed image {image_id}:\n"
                    f"{full_error}\n"
                )

                return empty_result_row(
                    folder_id=folder_id,
                    image_id=image_id,
                    status="FAILED",
                    error=full_error
                )

            except Exception as error:
                error_text = str(error).upper()

                transient_markers = [
                    "429",
                    "500",
                    "502",
                    "503",
                    "504",
                    "RESOURCE_EXHAUSTED",
                    "RATE",
                    "QUOTA",
                    "LIMIT",
                    "OVERLOADED",
                    "UNAVAILABLE",
                    "TIMEOUT",
                    "TIMED OUT",
                    "CONNECTION",
                    "CONNECTION RESET",
                    "INTERNAL"
                ]

                is_transient = any(
                    marker in error_text
                    for marker in transient_markers
                )

                has_retry_remaining = (
                    attempt < GEMINI_RETRIES - 1
                )

                if (
                    is_transient
                    and has_retry_remaining
                ):
                    wait_time = (
                        (2 ** attempt)
                        + random.uniform(1, 3)
                    )

                    print(
                        f"⚠️ API error on {image_id}. "
                        f"Retry {attempt + 1}/"
                        f"{GEMINI_RETRIES} "
                        f"in {wait_time:.1f}s..."
                    )

                    await asyncio.sleep(
                        wait_time
                    )

                    continue

                full_error = (
                    f"{type(error).__name__}: "
                    f"{repr(error)}"
                )

                print(
                    f"\n❌ Failed image {image_id}:\n"
                    f"{full_error}\n"
                )

                return empty_result_row(
                    folder_id=folder_id,
                    image_id=image_id,
                    status="FAILED",
                    error=full_error
                )

        return empty_result_row(
            folder_id=folder_id,
            image_id=image_id,
            status="FAILED",
            error="Maximum Gemini retries exceeded."
        )


# ============================================================
# 12. SAVE OR UPDATE CHECKPOINT
# ============================================================

def save_checkpoint(
    batch_results
):
    """
    Merge retry results with the existing CSV.

    New rows are placed before old rows. Therefore,
    drop_duplicates(..., keep="first") replaces old FAILED
    rows with the newest retry result.
    """

    new_df = pd.DataFrame(
        batch_results
    ).reindex(
        columns=OUTPUT_COLUMNS
    )

    new_df["folder_id"] = (
        new_df["folder_id"]
        .astype(str)
    )

    new_df["image_id"] = (
        new_df["image_id"]
        .astype(str)
    )

    if os.path.exists(CSV_PATH):

        existing_df = pd.read_csv(
            CSV_PATH,
            on_bad_lines="skip",
            dtype={
                "folder_id": str,
                "image_id": str
            }
        ).reindex(
            columns=OUTPUT_COLUMNS
        )

        existing_df["folder_id"] = (
            existing_df["folder_id"]
            .astype(str)
        )

        existing_df["image_id"] = (
            existing_df["image_id"]
            .astype(str)
        )

        combined_df = pd.concat(
            [
                new_df,
                existing_df
            ],
            ignore_index=True
        )

        combined_df = combined_df.drop_duplicates(
            subset=[
                "folder_id",
                "image_id"
            ],
            keep="first"
        )

    else:
        combined_df = new_df

    combined_df = combined_df.sort_values(
        [
            "folder_id",
            "image_id"
        ]
    ).reset_index(
        drop=True
    )

    temporary_path = (
        CSV_PATH
        + ".tmp"
    )

    combined_df.to_csv(
        temporary_path,
        index=False
    )

    os.replace(
        temporary_path,
        CSV_PATH
    )

    return combined_df


# ============================================================
# 13. MAIN ASYNC COORDINATOR
# ============================================================

async def main():

    processed_images = set()

    # --------------------------------------------------------
    # Load existing successful images
    # --------------------------------------------------------

    if (
        os.path.exists(CSV_PATH)
        and not START_FRESH
    ):
        try:
            existing_df = pd.read_csv(
                CSV_PATH,
                on_bad_lines="skip",
                dtype={
                    "folder_id": str,
                    "image_id": str
                }
            )

            required_checkpoint_columns = {
                "folder_id",
                "image_id",
                "status"
            }

            missing_checkpoint_columns = (
                required_checkpoint_columns
                - set(existing_df.columns)
            )

            if missing_checkpoint_columns:
                raise ValueError(
                    "Existing CSV is missing required columns: "
                    f"{sorted(missing_checkpoint_columns)}"
                )

            existing_df["folder_id"] = (
                existing_df["folder_id"]
                .astype(str)
            )

            existing_df["image_id"] = (
                existing_df["image_id"]
                .astype(str)
            )

            success_df = existing_df[
                existing_df["status"].eq(
                    "SUCCESS"
                )
            ].copy()

            processed_images = set(
                zip(
                    success_df["folder_id"],
                    success_df["image_id"]
                )
            )

            print(
                f"🔄 Checkpoint loaded: "
                f"{len(processed_images):,} images "
                f"successfully completed."
            )

            print(
                "\nExisting checkpoint status counts:"
            )

            print(
                existing_df["status"]
                .value_counts(dropna=False)
            )

        except Exception as error:
            raise RuntimeError(
                "Could not safely load the existing "
                "checkpoint:\n"
                f"{type(error).__name__}: {error}"
            )


    # --------------------------------------------------------
    # Find the nine PUMA folders
    # --------------------------------------------------------

    subfolders = sorted(
        [
            folder_name
            for folder_name in os.listdir(
                BASE_DIR
            )
            if re.fullmatch(
                r"260\d{4}",
                folder_name
            )
            and os.path.isdir(
                os.path.join(
                    BASE_DIR,
                    folder_name
                )
            )
        ]
    )

    print(
        f"\n📂 Found {len(subfolders)} "
        f"PUMA subfolders:"
    )

    for folder_name in subfolders:
        print(folder_name)

    if len(subfolders) != 9:
        raise ValueError(
            f"Expected 9 PUMA folders, "
            f"but found {len(subfolders)}:\n"
            f"{subfolders}"
        )


    # --------------------------------------------------------
    # Gather only images not already marked SUCCESS
    # --------------------------------------------------------

    all_image_tasks = []

    total_images_found = 0
    skipped_successful = 0

    for folder_id in subfolders:

        folder_path = os.path.join(
            BASE_DIR,
            folder_id
        )

        image_files = sorted(
            [
                filename
                for filename in os.listdir(
                    folder_path
                )
                if filename.lower().endswith(
                    (
                        ".jpg",
                        ".jpeg"
                    )
                )
            ]
        )

        total_images_found += len(
            image_files
        )

        for image_filename in image_files:

            image_id = re.sub(
                r"\D",
                "",
                image_filename
            )

            key = (
                str(folder_id),
                str(image_id)
            )

            if (
                not START_FRESH
                and key in processed_images
            ):
                skipped_successful += 1
                continue

            file_path = os.path.join(
                folder_path,
                image_filename
            )

            all_image_tasks.append(
                (
                    folder_id,
                    image_id,
                    file_path
                )
            )


    total_tasks = len(
        all_image_tasks
    )

    print(
        f"\n🖼️ Total images found: "
        f"{total_images_found:,}"
    )

    print(
        f"✅ Previously successful images skipped: "
        f"{skipped_successful:,}"
    )

    print(
        f"🔁 Images remaining for processing or retry: "
        f"{total_tasks:,}"
    )

    if total_tasks == 0:
        print(
            "\n🎉 All images are already marked SUCCESS."
        )

        return


    # --------------------------------------------------------
    # Processing settings
    # --------------------------------------------------------

    semaphore = asyncio.Semaphore(
        MAX_CONCURRENT_TASKS
    )

    total_batches = (
        total_tasks
        + CHUNK_SIZE
        - 1
    ) // CHUNK_SIZE


    # --------------------------------------------------------
    # Process and checkpoint each small retry batch
    # --------------------------------------------------------

    for start_index in range(
        0,
        total_tasks,
        CHUNK_SIZE
    ):

        batch_number = (
            start_index
            // CHUNK_SIZE
        ) + 1

        chunk = all_image_tasks[
            start_index:
            start_index + CHUNK_SIZE
        ]

        print(
            f"\n⚙️ Processing retry batch "
            f"{batch_number} / "
            f"{total_batches}..."
        )

        tasks = [
            analyze_image(
                semaphore=semaphore,
                folder_id=folder_id,
                image_id=image_id,
                file_path=file_path
            )
            for (
                folder_id,
                image_id,
                file_path
            ) in chunk
        ]

        batch_results = await asyncio.gather(
            *tasks,
            return_exceptions=False
        )

        combined_df = save_checkpoint(
            batch_results
        )

        batch_df = pd.DataFrame(
            batch_results
        )

        batch_status_counts = (
            batch_df["status"]
            .value_counts(
                dropna=False
            )
        )

        completed_in_retry = min(
            start_index + len(chunk),
            total_tasks
        )

        print(
            f"💾 Checkpoint saved. "
            f"Retry progress: "
            f"{completed_in_retry:,} "
            f"/ {total_tasks:,}"
        )

        print(
            "\nRetry batch statuses:"
        )

        print(
            batch_status_counts
        )

        print(
            f"\nRows currently stored in run2 CSV: "
            f"{len(combined_df):,}"
        )


    # --------------------------------------------------------
    # Final verification
    # --------------------------------------------------------

    final_df = pd.read_csv(
        CSV_PATH,
        on_bad_lines="skip",
        dtype={
            "folder_id": str,
            "image_id": str
        }
    )

    duplicate_count = final_df.duplicated(
        subset=[
            "folder_id",
            "image_id"
        ]
    ).sum()

    final_status_counts = (
        final_df["status"]
        .value_counts(
            dropna=False
        )
    )

    success_count = (
        final_df["status"]
        .eq("SUCCESS")
        .sum()
    )

    failed_final = final_df[
        final_df["status"].ne(
            "SUCCESS"
        )
    ].copy()

    print(
        "\n🎉 Run 2 retry pass finished."
    )

    print(
        "\nFinal output:"
    )

    print(
        CSV_PATH
    )

    print(
        "\nFinal row count:"
    )

    print(
        len(final_df)
    )

    print(
        "\nFinal status counts:"
    )

    print(
        final_status_counts
    )

    print(
        "\nDuplicate folder_id + image_id pairs:"
    )

    print(
        duplicate_count
    )

    if (
        len(final_df) == total_images_found
        and success_count == total_images_found
        and duplicate_count == 0
    ):
        print(
            "\n✅ PERFECT FINAL CHECK:"
        )

        print(
            f"All {total_images_found:,} images are "
            "recorded exactly once and marked SUCCESS."
        )

    else:
        print(
            "\n⚠️ Final file still requires review."
        )

        print(
            f"Remaining non-success rows: "
            f"{len(failed_final):,}"
        )

        if len(failed_final) > 0:
            print(
                "\nMost common remaining errors:"
            )

            print(
                failed_final["error"]
                .value_counts(
                    dropna=False
                )
                .head(10)
            )

            print(
                "\nRemaining failed image IDs:"
            )

            print(
                failed_final[
                    [
                        "folder_id",
                        "image_id",
                        "error"
                    ]
                ].to_string(
                    index=False
                )
            )


# ============================================================
# 14. LAUNCH RUN 2 RETRY PASS
# ============================================================

await main()







test_path = (
    "/content/drive/MyDrive/Georgetown run/"
    "radius/2600100/101506.jpg"
)

with open(test_path, "rb") as f:
    test_bytes = f.read()

print("Bytes read:", len(test_bytes))





# replace this
try:
    with open(file_path, "rb") as image_file:
        image_bytes = image_file.read()

except Exception as error:
    return empty_result_row(
        folder_id=folder_id,
        image_id=image_id,
        status="FAILED",
        error=(
            f"Failed to read file: "
            f"{type(error).__name__}: {error}"
        )
    )

image_bytes = None
file_read_retries = 5

for read_attempt in range(file_read_retries):
    try:
        with open(file_path, "rb") as image_file:
            image_bytes = image_file.read()

        break

    except OSError as error:
        has_retry_remaining = (
            read_attempt < file_read_retries - 1
        )

        if has_retry_remaining:
            wait_time = (
                2 ** read_attempt
                + random.uniform(0.5, 1.5)
            )

            print(
                f"⚠️ Drive read error on {image_id}. "
                f"Retry {read_attempt + 1}/{file_read_retries} "
                f"in {wait_time:.1f}s..."
            )

            await asyncio.sleep(wait_time)
            continue

        return empty_result_row(
            folder_id=folder_id,
            image_id=image_id,
            status="FAILED",
            error=(
                f"Failed to read file after "
                f"{file_read_retries} attempts: "
                f"{type(error).__name__}: {error}"
            )
        )

    except Exception as error:
        return empty_result_row(
            folder_id=folder_id,
            image_id=image_id,
            status="FAILED",
            error=(
                f"Failed to read file: "
                f"{type(error).__name__}: {error}"
            )
        )