# -*- coding: utf-8 -*-
"""intersection imagery collection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GExThxAj7spcOgLuRrK3-Fz2Vkq9-Hni
"""

from google.colab import drive
drive.mount("/content/drive")

from pathlib import Path

input_path = Path(
    "/content/drive/MyDrive/Georgetown run/"
    "nearest_intersections_all_locations.csv"
)

print(input_path.exists())
print(input_path)

!pip install streetlevel

from streetlevel import streetview
print("streetlevel imported successfully")



"""# collection

"""

# ============================================================
# Download one GSV panorama per nearest-intersection location
#
# Input:
#   /content/drive/MyDrive/Georgetown run/
#       nearest_intersections_all_locations.csv
#
# Images:
#   /content/drive/MyDrive/Georgetown run/
#       intersection imagery/<pumaid>/<point_id>.jpg
#
# Metadata:
#   intersection imagery/
#       intersection_gsv_download_metadata.csv
#       intersection_gsv_download_summary_by_puma.csv
#
# Important:
#   - GSV is searched using intersection_lat/intersection_lon.
#   - Images are named using point_id.
#   - Images are organized into folders using pumaid.
#   - Existing nonempty images are skipped.
# ============================================================

from pathlib import Path
import asyncio
import random
import time

import aiohttp
import pandas as pd
from tqdm.auto import tqdm
from streetlevel import streetview


# ============================================================
# 0. PATHS
# ============================================================

INPUT_CSV = Path(
    "/content/drive/MyDrive/Georgetown run/"
    "nearest_intersections_all_locations.csv"
)

OUTPUT_DIR = Path(
    "/content/drive/MyDrive/Georgetown run/"
    "intersection imagery"
)

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

DOWNLOAD_META_CSV = (
    OUTPUT_DIR / "intersection_gsv_download_metadata.csv"
)

SUMMARY_CSV = (
    OUTPUT_DIR / "intersection_gsv_download_summary_by_puma.csv"
)


# ============================================================
# 1. SETTINGS
# ============================================================

# Search radius around the nearest-intersection coordinate.
RADIUS_M = 80

# Panorama download resolution.
ZOOM = 5

# Number of simultaneous downloads.
# Start with 20. Reduce to 10 if many requests fail.
CONCURRENCY = 30

# Total timeout for one HTTP operation.
TIMEOUT_SECONDS = 180

# Number of attempts for each point.
MAX_ATTEMPTS = 3

# Delay between retries.
RETRY_BASE_DELAY_SECONDS = 2

# Number of rows processed before checkpoint metadata is saved.
BATCH_SIZE = 500

# Treat an existing file as valid only when it exceeds this size.
MIN_VALID_IMAGE_BYTES = 1_000


# ============================================================
# 2. HELPER FUNCTIONS
# ============================================================

def clean_id(value):
    """
    Convert an ID to a clean string.

    This prevents integer-like IDs read as floats from becoming
    filenames such as 12345.0.jpg.
    """
    if pd.isna(value):
        return None

    text = str(value).strip()

    if text.endswith(".0"):
        numeric_part = text[:-2]

        if numeric_part.isdigit():
            text = numeric_part

    return text


def valid_existing_image(path):
    """
    Return True only when the image exists and is nonempty.
    """
    return (
        path.exists()
        and path.is_file()
        and path.stat().st_size >= MIN_VALID_IMAGE_BYTES
    )


def get_pano_attribute(pano, possible_names):
    """
    Safely retrieve a panorama attribute when streetlevel versions
    use slightly different attribute names.
    """
    for name in possible_names:
        value = getattr(pano, name, None)

        if value is not None:
            return value

    return None


def normalize_metadata_value(value):
    """
    Convert unusual metadata values into CSV-safe values.
    """
    if value is None:
        return None

    if isinstance(value, (str, int, float, bool)):
        return value

    return str(value)


def save_checkpoint(metadata_rows):
    """
    Save current metadata and a summary by PUMA/status.
    """
    if not metadata_rows:
        return

    metadata = pd.DataFrame(metadata_rows)

    if "point_id" in metadata.columns:
        metadata["point_id"] = metadata["point_id"].astype(str)

        # Keep the most recent result if a point somehow appears twice.
        metadata = metadata.drop_duplicates(
            subset=["point_id"],
            keep="last"
        )

    metadata.to_csv(
        DOWNLOAD_META_CSV,
        index=False,
        encoding="utf-8-sig"
    )

    if {
        "pumaid",
        "download_status"
    }.issubset(metadata.columns):

        summary = (
            metadata
            .groupby(
                ["pumaid", "download_status"],
                dropna=False
            )
            .size()
            .reset_index(name="n")
            .sort_values(
                ["pumaid", "download_status"]
            )
        )

        summary.to_csv(
            SUMMARY_CSV,
            index=False,
            encoding="utf-8-sig"
        )


# ============================================================
# 3. LOAD AND VALIDATE INTERSECTION FILE
# ============================================================

if not INPUT_CSV.exists():
    raise FileNotFoundError(
        f"Input file not found:\n{INPUT_CSV}"
    )

download_frame = pd.read_csv(
    INPUT_CSV,
    dtype={
        "point_id": str,
        "msgid": str,
        "pumaid": str,
    }
)

# Support a file that uses msgid instead of point_id.
if (
    "point_id" not in download_frame.columns
    and "msgid" in download_frame.columns
):
    download_frame = download_frame.rename(
        columns={"msgid": "point_id"}
    )

required_columns = [
    "point_id",
    "pumaid",
    "intersection_lat",
    "intersection_lon",
]

missing_columns = [
    column
    for column in required_columns
    if column not in download_frame.columns
]

if missing_columns:
    raise ValueError(
        "The nearest-intersection file is missing required columns:\n"
        f"{missing_columns}\n\n"
        "Available columns:\n"
        f"{download_frame.columns.tolist()}"
    )

# Clean IDs.
download_frame["point_id"] = (
    download_frame["point_id"]
    .apply(clean_id)
)

download_frame["pumaid"] = (
    download_frame["pumaid"]
    .apply(clean_id)
)

# Convert intersection coordinates to numeric.
download_frame["intersection_lat"] = pd.to_numeric(
    download_frame["intersection_lat"],
    errors="coerce"
)

download_frame["intersection_lon"] = pd.to_numeric(
    download_frame["intersection_lon"],
    errors="coerce"
)

# Identify invalid rows.
invalid_id = (
    download_frame["point_id"].isna()
    | download_frame["pumaid"].isna()
)

invalid_coordinates = (
    download_frame["intersection_lat"].isna()
    | download_frame["intersection_lon"].isna()
    | ~download_frame["intersection_lat"].between(-90, 90)
    | ~download_frame["intersection_lon"].between(-180, 180)
)

invalid_rows = invalid_id | invalid_coordinates

print("=" * 70)
print("INPUT CHECK")
print("=" * 70)
print(f"Input file: {INPUT_CSV}")
print(f"Output directory: {OUTPUT_DIR}")
print(f"Total rows: {len(download_frame):,}")
print(
    "Unique point IDs:",
    f"{download_frame['point_id'].nunique(dropna=True):,}"
)
print(
    "Unique PUMAs:",
    f"{download_frame['pumaid'].nunique(dropna=True):,}"
)
print(f"Invalid rows: {int(invalid_rows.sum()):,}")

if download_frame["point_id"].duplicated().any():
    duplicate_ids = (
        download_frame.loc[
            download_frame["point_id"].duplicated(
                keep=False
            ),
            "point_id"
        ]
        .dropna()
        .unique()
    )

    raise ValueError(
        "point_id must be unique, but duplicates were found.\n"
        f"Example duplicate IDs: {duplicate_ids[:10].tolist()}"
    )

if invalid_rows.any():
    print("\nExamples of invalid rows:")

    display(
        download_frame.loc[
            invalid_rows,
            required_columns
        ].head(20)
    )

# Keep valid rows only.
to_download = (
    download_frame.loc[~invalid_rows]
    .copy()
    .reset_index(drop=True)
)

# Create one output folder for each PUMA.
pumaids = sorted(
    to_download["pumaid"].dropna().unique()
)

for pumaid in pumaids:
    (OUTPUT_DIR / pumaid).mkdir(
        parents=True,
        exist_ok=True
    )

print("\nRows by PUMA:")

puma_counts = (
    to_download
    .groupby("pumaid")
    .size()
    .reset_index(name="n_locations")
    .sort_values("pumaid")
)

display(puma_counts)

print("PUMA folders created:", len(pumaids))
print("PUMA IDs:", pumaids)

if len(pumaids) != 9:
    print(
        "\nWARNING: The valid data contain "
        f"{len(pumaids)} PUMAs rather than 9."
    )


# ============================================================
# 4. LOAD PREVIOUS DOWNLOAD METADATA, WHEN AVAILABLE
# ============================================================

previous_metadata = pd.DataFrame()

if DOWNLOAD_META_CSV.exists():
    try:
        previous_metadata = pd.read_csv(
            DOWNLOAD_META_CSV,
            dtype={
                "point_id": str,
                "msgid": str,
                "pumaid": str,
            }
        )

        if (
            "point_id" not in previous_metadata.columns
            and "msgid" in previous_metadata.columns
        ):
            previous_metadata["point_id"] = (
                previous_metadata["msgid"]
            )

        if "point_id" in previous_metadata.columns:
            previous_metadata["point_id"] = (
                previous_metadata["point_id"]
                .apply(clean_id)
            )

            previous_metadata = (
                previous_metadata
                .drop_duplicates(
                    subset=["point_id"],
                    keep="last"
                )
            )

        print(
            "\nPrevious metadata rows loaded:",
            f"{len(previous_metadata):,}"
        )

    except Exception as error:
        print(
            "\nWARNING: Existing metadata could not be read."
        )
        print(
            f"{type(error).__name__}: {error}"
        )

        previous_metadata = pd.DataFrame()


# ============================================================
# 5. DOWNLOAD ONE IMAGE
# ============================================================

async def download_one_gsv(
    session,
    row,
    semaphore
):
    point_id = str(row["point_id"])
    pumaid = str(row["pumaid"])

    intersection_lat = float(
        row["intersection_lat"]
    )

    intersection_lon = float(
        row["intersection_lon"]
    )

    puma_dir = OUTPUT_DIR / pumaid
    puma_dir.mkdir(
        parents=True,
        exist_ok=True
    )

    image_path = (
        puma_dir / f"{point_id}.jpg"
    )

    result = {
        "point_id": point_id,
        "msgid": point_id,
        "pumaid": pumaid,

        # Original sampled location, when present.
        "query_lat": row.get(
            "query_lat",
            None
        ),
        "query_lon": row.get(
            "query_lon",
            None
        ),

        # Intersection used for the GSV search.
        "intersection_lat": intersection_lat,
        "intersection_lon": intersection_lon,

        # Nearest-intersection distance, when present.
        "distance_to_intersection_m": row.get(
            "distance_to_intersection_m",
            row.get(
                "nearest_intersection_distance_m",
                row.get(
                    "distance_m",
                    None
                )
            )
        ),

        "image_path": str(image_path),

        # GSV panorama metadata.
        "gsv_source_id": None,
        "gsv_capture_date": None,
        "gsv_source_lat": None,
        "gsv_source_lon": None,

        "download_status": None,
        "download_error": None,
        "attempts_used": 0,
        "file_size_bytes": None,
    }

    # Resume behavior: skip an already valid image.
    if valid_existing_image(image_path):
        result["download_status"] = (
            "skipped_exists"
        )

        result["file_size_bytes"] = (
            image_path.stat().st_size
        )

        return result

    # Remove a corrupt or empty file before retrying.
    if image_path.exists():
        try:
            image_path.unlink()
        except Exception:
            pass

    async with semaphore:
        # Small stagger prevents all requests from starting
        # at precisely the same instant.
        await asyncio.sleep(
            random.uniform(0.05, 0.20)
        )

        for attempt in range(
            1,
            MAX_ATTEMPTS + 1
        ):
            result["attempts_used"] = attempt

            try:
                pano = (
                    await streetview
                    .find_panorama_async(
                        intersection_lat,
                        intersection_lon,
                        session,
                        radius=RADIUS_M
                    )
                )

                if pano is None:
                    result["download_status"] = (
                        "no_pano_at_intersection"
                    )

                    return result

                result["gsv_source_id"] = (
                    normalize_metadata_value(
                        get_pano_attribute(
                            pano,
                            [
                                "id",
                                "pano_id",
                                "source_id",
                            ]
                        )
                    )
                )

                result["gsv_capture_date"] = (
                    normalize_metadata_value(
                        get_pano_attribute(
                            pano,
                            [
                                "date",
                                "capture_date",
                            ]
                        )
                    )
                )

                result["gsv_source_lat"] = (
                    normalize_metadata_value(
                        get_pano_attribute(
                            pano,
                            [
                                "lat",
                                "latitude",
                            ]
                        )
                    )
                )

                result["gsv_source_lon"] = (
                    normalize_metadata_value(
                        get_pano_attribute(
                            pano,
                            [
                                "lon",
                                "lng",
                                "longitude",
                            ]
                        )
                    )
                )

                await streetview.download_panorama_async(
                    pano,
                    path=str(image_path),
                    session=session,
                    zoom=ZOOM
                )

                if valid_existing_image(image_path):
                    result["download_status"] = "ok"
                    result["download_error"] = None
                    result["file_size_bytes"] = (
                        image_path.stat().st_size
                    )

                    return result

                # Remove an incomplete download.
                if image_path.exists():
                    try:
                        image_path.unlink()
                    except Exception:
                        pass

                raise OSError(
                    "The panorama download completed, "
                    "but the output image is missing "
                    "or too small."
                )

            except Exception as error:
                result["download_error"] = (
                    f"{type(error).__name__}: {error}"
                )

                if image_path.exists():
                    try:
                        if not valid_existing_image(
                            image_path
                        ):
                            image_path.unlink()
                    except Exception:
                        pass

                if attempt < MAX_ATTEMPTS:
                    delay = (
                        RETRY_BASE_DELAY_SECONDS
                        * attempt
                        + random.uniform(0, 1)
                    )

                    await asyncio.sleep(delay)

        result["download_status"] = (
            "error_after_retries"
        )

        return result


# ============================================================
# 6. PROCESS ONE BATCH
# ============================================================

async def run_batch(
    batch_df,
    session,
    semaphore
):
    tasks = [
        asyncio.create_task(
            download_one_gsv(
                session,
                row,
                semaphore
            )
        )
        for _, row in batch_df.iterrows()
    ]

    results = []

    for task in tqdm(
        asyncio.as_completed(tasks),
        total=len(tasks),
        desc="Downloading batch",
        leave=False
    ):
        results.append(await task)

    return results


# ============================================================
# 7. RUN ALL DOWNLOADS WITH CHECKPOINTING
# ============================================================

async def run_all_downloads(
    download_df
):
    timeout = aiohttp.ClientTimeout(
        total=TIMEOUT_SECONDS
    )

    connector = aiohttp.TCPConnector(
        limit=CONCURRENCY,
        limit_per_host=CONCURRENCY
    )

    semaphore = asyncio.Semaphore(
        CONCURRENCY
    )

    # Start from previous metadata so it is preserved.
    metadata_by_point = {}

    if (
        not previous_metadata.empty
        and "point_id"
        in previous_metadata.columns
    ):
        for record in (
            previous_metadata
            .to_dict("records")
        ):
            point_id = clean_id(
                record.get("point_id")
            )

            if point_id is not None:
                metadata_by_point[point_id] = (
                    record
                )

    total_batches = (
        len(download_df)
        + BATCH_SIZE
        - 1
    ) // BATCH_SIZE

    async with aiohttp.ClientSession(
        timeout=timeout,
        connector=connector
    ) as session:

        for batch_number, start_index in enumerate(
            range(
                0,
                len(download_df),
                BATCH_SIZE
            ),
            start=1
        ):
            end_index = min(
                start_index + BATCH_SIZE,
                len(download_df)
            )

            batch_df = download_df.iloc[
                start_index:end_index
            ]

            print(
                f"\nBatch {batch_number}/{total_batches}: "
                f"rows {start_index + 1:,}"
                f"–{end_index:,}"
            )

            batch_results = await run_batch(
                batch_df,
                session,
                semaphore
            )

            for record in batch_results:
                metadata_by_point[
                    str(record["point_id"])
                ] = record

            current_metadata = list(
                metadata_by_point.values()
            )

            save_checkpoint(
                current_metadata
            )

            batch_status = (
                pd.DataFrame(batch_results)
                ["download_status"]
                .value_counts(dropna=False)
            )

            print("Batch result:")
            print(batch_status.to_string())

            print(
                "Checkpoint saved:",
                DOWNLOAD_META_CSV
            )

    final_metadata = pd.DataFrame(
        list(metadata_by_point.values())
    )

    return final_metadata


# ============================================================
# 8. EXECUTE
# ============================================================

print("\n" + "=" * 70)
print("STARTING INTERSECTION GSV DOWNLOAD")
print("=" * 70)
print(f"Search radius: {RADIUS_M} m")
print(f"Zoom: {ZOOM}")
print(f"Concurrency: {CONCURRENCY}")
print(f"Maximum attempts: {MAX_ATTEMPTS}")
print(f"Batch size: {BATCH_SIZE}")
print(f"Locations to process: {len(to_download):,}")

start_time = time.time()

download_metadata = await run_all_downloads(
    to_download
)

elapsed_minutes = (
    time.time() - start_time
) / 60

save_checkpoint(
    download_metadata.to_dict("records")
)

print("\n" + "=" * 70)
print("FINAL DOWNLOAD REPORT")
print("=" * 70)
print(
    "Elapsed time:",
    f"{elapsed_minutes:.2f} minutes"
)
print(
    "Metadata rows:",
    f"{len(download_metadata):,}"
)

if not download_metadata.empty:
    print("\nDownload statuses:")

    print(
        download_metadata[
            "download_status"
        ]
        .value_counts(dropna=False)
        .to_string()
    )


# ============================================================
# 9. VERIFY FILE COUNTS BY PUMA
# ============================================================

image_count_rows = []

for pumaid in pumaids:
    puma_dir = OUTPUT_DIR / pumaid

    valid_images = [
        image_path
        for image_path in puma_dir.glob("*.jpg")
        if valid_existing_image(image_path)
    ]

    expected_count = int(
        (
            to_download["pumaid"]
            == pumaid
        ).sum()
    )

    image_count_rows.append(
        {
            "pumaid": pumaid,
            "expected_points": expected_count,
            "valid_image_files": len(
                valid_images
            ),
            "difference": (
                len(valid_images)
                - expected_count
            ),
        }
    )

image_counts = pd.DataFrame(
    image_count_rows
)

print("\nValid image counts by PUMA:")
display(image_counts)

print("\nMetadata saved to:")
print(DOWNLOAD_META_CSV)

print("\nSummary saved to:")
print(SUMMARY_CSV)

print("\nImages saved under:")
print(OUTPUT_DIR)

print("\nExample image location:")
print(
    OUTPUT_DIR
    / "<pumaid>"
    / "<point_id>.jpg"
)

